### ISSUE TITLE
HTML5 video autoplay not working

### ISSUE THREAD

**Issue by ibenzal** [impress/impress.js#100]
Hiya,

I have a video tag with the autoplay attribute set to true and the framework render the video but it starts stopped.

```
 <section class="step container" data-x="0" data-y="0">
        <video autoplay>
            <source id="coverVideo" src="videos/FlowsCover.mp4" type='video/mp4'/>
        </video>
    </section>
```

If I move this code to a section outside the "impress" div, it works fine. 

Best,
Iban

**Comment by matejmosko** [comment]
Hi, I have stumbled upon the same problem when creating my own impress.js player app (electron). In my case I don't have an access to do presentation files, so I cannot manually assign ids to video slides. Therefore I have created more general-purpose solution. This solution does not need you to change anything in your presentation, just call this peace of code somewhere after impress().init()

```
var videos = document.getElementsByTagName("video");
    Array.prototype.forEach.call(videos, function(el) {
      var videoStep = el.closest(".step");
      videoStep.addEventListener("impress:stepenter", function() {
          el.play();
      }, false);
      videoStep.addEventListener("impress:stepleave", function() {
          el.pause();
      }, false);
    });
```

As you can see. It searches for video tags in your presentation and for every video tag it adds an EventListener for parent .step. It can be done for audio tags as well.
