### ISSUE TITLE
Ignore arrow keys when event.metaKey.

### ISSUE THREAD

**Issue by mbostock** [impress/impress.js#116]
Currently, impress.js breaks keyboard shortcuts for the browser's Back (⌘←) and Forward (⌘→) because it swallows all keyup events without first checking `event.metaKey`. You'll probably want to do some filtering around [impress.js:425](https://github.com/bartaz/impress.js/blob/master/js/impress.js#L424-443). For comparison, see my implementation in [stack.js](https://github.com/mbostock/stack/blob/gh-pages/stack.v0.js#L88-110).

**Comment by henrikingo** [comment]
Isn't this bug fixed by this commit: https://github.com/impress/impress.js/commit/d8995aa3194f6fdbcc8867626d52f913d0c52882

**Comment by FagnerMartinsBrack** [comment]
> Isn't this bug fixed by this commit: d8995aa

I guess I didn't closed this in the first triage because we need to check it to make sure. Since that code doesn't have test coverage, I am not sure if we can consider this as "really" fixed.

**Comment by henrikingo** [comment]
This is now fixed in master branch.
