### ISSUE TITLE
Focus trouble with negatives data-z property

### ISSUE THREAD

**Issue by florianharmel** [impress/impress.js#164]
Hello,

I saw troubles on form elements focuses when a step has a negative data-z property.
Even if there is only one slide.

have you already noticed something like that ?

Cordially,
Florian

**Comment by FagnerMartinsBrack** [comment]
Hi @florianharmel, @Earthwings, @scbritton, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

Can anybody confirm if this is was indeed a browser bug and if the issue still exists? A simplified example would help a lot.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
