### ISSUE TITLE
On scroll/move event handler?

### ISSUE THREAD

**Issue by iluxav** [impress/impress.js#167]
Hi,

Is there a event handler like onScroll or onMove? 

I'm trying to build a uml diagram presentation, where i have DIV's connected with lines between them. 
The problem is when I loading the page it draws lines perfect, even after scrolling to another div,  however i cannot find any event that could redraw the lines in real time(During the scrolling) and keep it connected even during the animation.

Thank you.

**Comment by FagnerMartinsBrack** [comment]
Hi @iluxav , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
