### ISSUE TITLE
Responsive scale problem

### ISSUE THREAD

**Issue by Valeka** [impress/impress.js#186]
Hi!

I'm not sure should I post these question here but I couldn't find answer anywhere. 
I created web site using impress.js and I have a problem now when I test my site in mobile devices (smaller screens). Everything looks great, well scaled only it is positioned on the screen center so user had to scroll a lot to see content. I tried to change css for smaller screen, I put some js to move content and 100 other things but nothing.

My site is on address http://valeka.net so if you have time you can take a look.

Sorry if this is not right place for this question, I know you cant review every single project.

Thanks!

**Comment by vladimirlisovets** [comment]
I did it by setting the min and max scale as same, and then just using media queries like I'd done in any other situation.
