### ISSUE TITLE
stop(); and restart() keyboard navigation handlers

### ISSUE THREAD

**Issue by whitedesign** [impress/impress.js#188]
Hi,
Fist of all, thanks for this great framework ;)
I use impress as an original "small website" and on one step there's a portfolio which is driven by keyboard navigation too.

I'd like to know if there's a way to "stop and restart" impress().api (in fact, just the keyboard navigation handlers.) to avoid conflict. (both slide and step advance... )
Any help will be appreciated!

Best regards from france

**Comment by FagnerMartinsBrack** [comment]
@dfernandeza This will probably be handled on https://github.com/impress/impress.js/issues/409.
