### ISSUE TITLE
Impress.js in HD

### ISSUE THREAD

**Issue by ghost** [impress/impress.js#197]
Hello, 

I have a problem with viewing my presentation on big resolution screens. 

Here is the sample slide on normal (1366x768) notebook screen:
http://imageshack.us/a/img440/7506/impress.png

And here is the same slide on HD screen:
http://imageshack.us/a/img809/2659/impresshd.png

I understand that all images and slides are sized in pixels and it has to be smaller on big resolution but is there any way to zoom a little bit? 

I tried ctrl+/ctrl- but some images and other element become invisible. 

I have also tried to prepare special copy for HD screens with data-scale atribute changed but it is not what I look for. Slides have the same relative size on the screen.

Do you have any ideas what can I do?

**Comment by ax3l** [comment]
I am trying to reproduce the `data-max-scale` behaviour but I can not get my images sharper.

My slide deck:
- slide 1: data-scale=8 with a full-screen image
- slide 2: data-scale=1 with a slide "above" the previous image (basically zoomed to a certain position of it)

as soon as I go to slide 2 the slide 1 resolution is not increased and the "background" provided by it pixels up...

Do you have an idea what I am missing?


```html
<div id="impress" data-width="1920" data-height="1080" data-max-scale="80">
    <div id="overview" class="step" data-x="0" data-y="0" data-z="-10" data-scale="8">
        <img alt="world map" src="img/my_large_background.svg" width="100%" />
    </div>
    <div id="title" class="step" data-x="0" data-y="-3000" data-z="200" data-rotate-x="-20">
        something
    </div>
</div>
