### ISSUE TITLE
show n-th slide again

### ISSUE THREAD

**Issue by blatan** [impress/impress.js#202]
Hi bartaz and all,
is there a simple way to show previous slide again?
For example

<code>&lt;div id="slide-1" class="slide"&gt;&lt;/div&gt;
&lt;div id="slide-2" class="slide"&gt;&lt;/div&gt;
&lt;div id="slide-3" class="slide"&gt;&lt;/div&gt;
&lt;div id="slide-1" class="slide"&gt;&lt;/div&gt;
&lt;div id="slide-4" class="slide"&gt;&lt;/div&gt;
</code>

And my second question.
I've got a big DB diagram image. I want to show tables one by one. But if I make a transparent slide the image is semi-translucent. How to make something like <code>img#DB {opacity: 1}</code> when another slide is active? It resolves the first problem as well.

Thanks in advance for helping me

**Comment by FagnerMartinsBrack** [comment]
Hi @blatan @briceparent , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) is still interested in keep it going.
