### ISSUE TITLE
Support HTML5 drag and drop inside impress.js

### ISSUE THREAD

**Issue by mminella** [impress/impress.js#205]
I am working on a presentation on HTML5 using the impress.js library and so far I have been able to include all of my examples directly into the presentation itself (which is the goal).  However, I have run into a snag.  It seems that when I attempt to use the HTML5 drag and drop functionality (specifically draggable="true" on a div in Chrome), it doesn't work.  The same code works when I disable impress.js on the page so I know that I'm using the functionality correctly.  I would hope that a library like this that relies on HTML5 so heavily (data elements, transitions, etc) that it wouldn't prevent me from using some of the other features.  Any insight that can be provided is appreciated.  Thanks in advance!

**Comment by henrikingo** [comment]
Based on above comment and lack of response, I assume this can be closed.
