### ISSUE TITLE
Unable to set a global background.

### ISSUE THREAD

**Issue by blackheaven** [impress/impress.js#208]
I tried to set a background to the map, but my image is cutted.
Here the code that I tried:
<code>
    #overview {
        background-image: url(../img/logo.svg);
        background-size: 100%;
        background-repeat: no-repeat;
    }
</code>

Only the top of the image is printed, is it a bug?
The complete source is here: https://github.com/blackheaven/postgresql-fdll-2012.
Thanks by advance.

**Comment by hokascha** [comment]
@bartaz your workaround works almost as expected for me. As my big image is really big the perfect solution for me would be to somehow "skip" the step containing the big image. Is there a way to skip a step in the presentation but this having the step on the screen positioned using data-x, data-y and data-z?

**Comment by benjaminellison** [comment]
I've just done something similar, although I made the div tag containing my large picture the very last div. All of the other divs/steps have no content... they're basically just viewport/stops along the big image. I had to tweak the style slightly so the "inactive" steps weren't alpha transparent, so my big image didn't fade out. With a bit of skew (rotation on X, Y), some changes in Z height, and once in a while a change to the scale, it makes for a very intriguing "fly over" tour of a very large schematic/diagram.

**Comment by FagnerMartinsBrack** [comment]
Duplicated of #544.
