### ISSUE TITLE
Scroll in an iframe inside a step

### ISSUE THREAD

**Issue by wikier** [impress/impress.js#210]
Trying to use a iframe inside one of my slides for a quick demo, I realized that the scroll doesn't work properly.  The scroll bar appears when needed, but it doesn't move the content of the frame source.

This is the code I'm using:

```
<div class="step" data-x="7850.666666666667" data-y="1638.4" data-scale="1" data-rotate="90"
   <div style="width: 1024px; height: 768px">
       <iframe width="1024" height="768" src="http://localhost/foo" frameborder="0" scrolling="yes" allowfullscreen></iframe>
    </div>
</div>
```

Do you have any idea if this is a problem of my usage, or iframes are not so well supported by impress.js?

Thanks in advance.

**Comment by henrikingo** [comment]
Hi @wikier 

I copied your code above into the examples/classic-slides/ presentation, and apart from the fact that the first line is missing the > scrolling totally works.

**Comment by henrikingo** [comment]
Closing due to lack of response. If the issue is still happening, please provide more info.
