### ISSUE TITLE
Chromium v22 seems to ignore data-z

### ISSUE THREAD

**Issue by fghaas** [impress/impress.js#216]
I'm guessing this is really not an impress.js issue, but perhaps someone is aware of a workaround or can at least confirm.

Presentations making use of `data-z` worked fine for me using Chromium v20 in Ubuntu precise, but since upgrading to v22 in quantal the z-axis no longer seems to work -- the presentation looks as if `data-z="0"`, no matter what the actual value is.

In Firefox 16 `data-z` is being honored as expected, but unfortunately its JS engine is so slow that it's really not an viable alternative for me to use.

**Comment by FagnerMartinsBrack** [comment]
Hi @fghaas, @bizmate, @jeroenvisser101, @zevero, @pyriand3r, @thomasjungblut , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

Can anybody confirm if the issue still exists? A simplified example would help a lot.

**Comment by fghaas** [comment]
Unfortunately I can't really comment as I now use reveal.js as my primary means of writing presentations, and haven't written a new deck in Impress for a while. But thanks for checking back!

**Comment by jeroenvisser101** [comment]
Same as @fghaas, haven't used it in a while, but if I have time I could check back on this.

**Comment by bizmate** [comment]
I will need to look at my repo on my codebase tonight or tomorrow night and I will let you know or push an example somewhere so you can review it

**Comment by FagnerMartinsBrack** [comment]
Thanks guys, looking forward to it!

**Comment by jeroenvisser101** [comment]
Not going to be tonight, maybe tomorrow morning/night

**Comment by pyriand3r** [comment]
Hey guys,
sorry for my late reply. I haven't used impress for a while, too, but i will check my presentations made with it. Hopefully i will find time today, but i can't promise it.

**Comment by pyriand3r** [comment]
I have tested it and data-z is working for me in chrome 48. Just added data-z to first slides of the demo presentation... works fine though.

**Comment by bizmate** [comment]
I think this can be closed now. I have checked and it all works as expected for me

**Comment by jeroenvisser101** [comment]
Same here, cannot seem to reproduce!

**Comment by FagnerMartinsBrack** [comment]
Thanks you very much for your effort guys! Closing then...
