### ISSUE TITLE
i get impress is not defined error with Meteor.js

### ISSUE THREAD

**Issue by crapthings** [impress/impress.js#218]
i put impress.js to project\client\js

open console type impress()

there's no object return, after i wrap whole impress.js code inside Meteor.startup ->

then i can use impress().init() in console to make impress.js working, but if i init() with

domready or meteor.startup i get impress is not defined

if impress.js loaded inside <head> <script>

how do i get it work ?

these two doesn't work

    Meteor.startup ->
        impress().init()

    $(document).ready ->
        impress().init()

**Comment by FagnerMartinsBrack** [comment]
Hi @crapthings, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

By the way, is there any action to take here or we can mark this as solved?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
