### ISSUE TITLE
'?' key should pop up keyboard shortcut help window

### ISSUE THREAD

**Issue by aspiers** [impress/impress.js#220]
'?' is being rapidly adopted as the standard keyboard shortcut for AJAX-ified web apps to pop up a help window listing useful information such as which shortcuts are supported for keyboard navigation etc.  Some examples:
- google mail
- google reader
- google calendar
- google news
- github
- Trello

It would be great if impress.js did this.  The help window could of course also link to the impress.js documentation and github site, which would help grow your community ;-)

**Comment by FagnerMartinsBrack** [comment]
Hi @aspiers , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

Do you have any links or examples that show if this standard still exists?

**Comment by aspiers** [comment]
Yes sure - I'm very much interested in seeing this implemented.  Some obvious examples:

- GitHub
- Gmail
- Google Calendar
- Google Drive
- Trello
- gerrit

but I am sure there are many others following the example of these very popular sites.

**Comment by aspiers** [comment]
Oh sorry, I just noticed I already gave a list in the original issue description :-)

**Comment by FagnerMartinsBrack** [comment]
> Oh sorry, I just noticed I already gave a list in the original issue description :-)

Yes I saw the list in the description, what I was asking was a demonstration of the feature. I want to verify how it exactly works to implement correctly if this is accepted and if the feature still exists in the services you mentioned. A link or a video using LICECap demonstrating the feature would be enough. Thank you!

**Comment by aspiers** [comment]
@FagnerMartinsBrack I think maybe you are fundamentally misunderstanding the feature request? Because you seem to think it's way more complicated than it actually is:

1. visit one of the sites I mentioned
2. press the '?' key
3. observe a popup window listing all the keyboard shortcuts available

You definitely don't need any videos for this!  It takes about 10 seconds per site to verify that they do it.

**Comment by FagnerMartinsBrack** [comment]
> I think maybe you are fundamentally misunderstanding the feature request? 

Yeah, I definitely misunderstood. Somehow I interpreted as a `?` in the querystring or something like that. Personally I never knew such feature existed consistently between services like these. Thanks :)

**Comment by aspiers** [comment]
Oh haha, OK :-)  Well hopefully now you can see how useful this feature is and agree with me that it would be awesome if impress.js had it ;-)

**Comment by aspiers** [comment]
Just checked and it seems that reveal.js also adopted this convention.

**Comment by FagnerMartinsBrack** [comment]
That's indeed very useful, it's on the list :)

**Comment by Pierstoval** [comment]
The problem is that the keyCode for `?` differs between countries, so I think we would need many workarounds for this :confused:

**Comment by aspiers** [comment]
Just find out how google do it and copy their solution :)

**Comment by Pierstoval** [comment]
Have you seen Google source code ? :laughing:

**Comment by FagnerMartinsBrack** [comment]
> The problem is that the keyCode for ? differs between countries, so I think we would need many workarounds for this

Very good point. If this differs between countries we cannot try to implement a generic solution because we might break the expectation from other users. It would be much more scalable to expose hooks that allow the developer to define the shortcuts and map the specific keys to them. I18n should be a responsibility of the application that is consuming impress.js, not impress.js itself.

This probably is also a problem for other shortcuts that use ASCII letters instead of control keys (such as page up, page down, left, right, etc.).

**Comment by Pierstoval** [comment]
We have to investigate more on this, I suggest to let the issue open until we found whether it's "easily feasible" or "too hard to do".

**Comment by FagnerMartinsBrack** [comment]
> We have to investigate more on this, I suggest to let the issue open until we found whether it's "easily feasible" or "too hard to do".

:+1:

**Comment by henrikingo** [comment]
Forgot to add yesterday, the help plugin already shows this kind of popup when you press 'H'. The scope of this ticket is to bind '?' to it as well.

**Comment by henrikingo** [comment]
#705 fixes this
