### ISSUE TITLE
'f' keyboard shortcut for full screen

### ISSUE THREAD

**Issue by aspiers** [impress/impress.js#221]
It would be great if 'f' was a keyboard shortcut for toggling full screen, just like on youtube etc.

**Comment by FagnerMartinsBrack** [comment]
Similarly related to #220.

**Comment by terrycloth** [comment]
Most browsers have a built-in full-screen mode, which get activated when you hit <kbd>F11</kbd>. What's the difference between that OP's feature request?

**Comment by aspiers** [comment]
Probably nothing, but browsers have not standardised on `F11`, and due to the popularity of sites like YouTube, plenty of people (even if not the majority) would expect `F` to work.

**Comment by henrikingo** [comment]
I'm gonna rule that this was now excellently implemented by #712 and this can be closed as a duplicate.

Note that #712 implemented the PowerPoint-standard F5 instead of f.
