### ISSUE TITLE
Implement screen "blackout"

### ISSUE THREAD

**Issue by hornos** [impress/impress.js#224]
http://prezi.com/learn/new-features/#blackout

**Comment by FagnerMartinsBrack** [comment]
@m42e Can you please link straight to your implementation of "screen blackout"?
@hornos Your link doesn't seem to be working anymore, do you have another resource we can take a look into that shows what "screen blackout" is all about?

Thanks guys and sorry for taking so long to answer!

**Comment by m42e** [comment]
https://github.com/m42e/impress.js/commit/f080c7cd118e9118c91e53ce06bd29f333afbdb5

**Comment by m42e** [comment]
Open PowerPoint in Presentation mode and press b I think :)

**Comment by henrikingo** [comment]
A `blackout` plugin, implemented by @Strikeskids in #372 is now merged to master.
