### ISSUE TITLE
"before-current" and "after-current" classes for steps

### ISSUE THREAD

**Issue by opatut** [impress/impress.js#230]
I think it would be great to have classes similar to `past` and `future`, but indicating whether a step is defined in code before the current one or after it, rather than only whether it has been visited.

This would be required to hide some objects that are not supposed to appear before a specific step has been reached, and that should disappear again when scrolling back.

**Comment by FagnerMartinsBrack** [comment]
@opatut Not sure if you are still tracking, but did you solved the problem using events? If yes, then there is no immediate reason for implementing a custom feature that can be already solved using the library provided mechanics.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
