### ISSUE TITLE
Slides show blank on Chrome / Windows

### ISSUE THREAD

**Issue by bizmate** [impress/impress.js#244]
Hi

I have noticed that after creating my presentation in Chrome from a Mac, in Windows this was not displaying well. I tried to understand why but so far i have not applied any magic CSS differently in Win Chrome as compared to Mac Chrome. 

This is the url where a reproduction of the presentation (images changed and text replaced with dummy) is 
http://bizmate.dreamhosters.com/impresstest

Would you be able so suggest what is wrong with it?

**Comment by FagnerMartinsBrack** [comment]
I have tried the original link of the OP and it is working fine in latest Chrome on Mac (49.0.2623.87 (64-bit)):

<img width="1428" alt="screenshot 2016-03-19 16 39 21" src="https://cloud.githubusercontent.com/assets/835857/13896871/438216f8-edf1-11e5-9e13-d68026d87b47.png">

I guess this was a temporary bug with the browser. Similar issues in the past also with other browsers: #382, #324, #443.
