### ISSUE TITLE
Presentation generator [...made by myself...]

### ISSUE THREAD

**Issue by cereal** [impress/impress.js#246]
Hey Guys,

I coded a small presentation generator in python. You can clone it from
```bash
git://github.com/cereal/impressive.git
```
Hope you'll enjoy it, send me your improvements by opening requests in
my repository. I'll add some features soon like white- and /blackout and the
impress console plugin (will integrate editing notes by config generator). 

Yours sincerly,
cereal

**Comment by abubelinha** [comment]
@cereal does it still exist somewhere else?
I don't use git but tried to browse https://github.com/cereal/impressive to no luck

Thanks
@abubelinha

**Comment by simplePCBuilding** [comment]
Doesn't look like it. I think there are some other tools out there

**Comment by simplePCBuilding** [comment]
If there are enough people interested I might consider to start building my own solution
