### ISSUE TITLE
Substeps in a step

### ISSUE THREAD

**Issue by davidfarina** [impress/impress.js#255]
Hi folks!

This may be a repetition of another issue.  But since the old issue never got a real answer i thought i could ask again for it; you guessed it, im asking for the functionality of substeps.

I dont really want a complex thing about it, i just want several divs in a step, which get the class active and past like normal steps, when you navigate through the presentation.

I hope you could help me, cause my css-only workaround doesnt worked.

Thanks in advance
David

**Comment by FagnerMartinsBrack** [comment]
> But since the old issue never got a real answer i thought i could ask again for it;

Sorry that the old issue didn't get a proper response. The project has been inactive for some time and the development is just starting to move again. So we are closing this as a duplicate of #81 and will be tracking this request in the old issue.

Thanks for opening the issue anyway!
