### ISSUE TITLE
rst2impress

### ISSUE THREAD

**Issue by pcav** [impress/impress.js#256]
It would be very useful if someone could write a converter from ReST to impress.js.
This should be reasonably easy, either modifying the
/usr/share/pyshared/docutils/writers/s5_html/__init__.py 

or by coding a custom `html_impress` writer inheriting most of the code  from the `html4css1` or `html4strict` writers. The `html4strict`__ writer  (in the sandbox) is also an example of a custom html writer.
  
  __ http://docutils.sourceforge.net/sandbox/html4strict/

I'm available to give a hand if needed.

**Comment by FagnerMartinsBrack** [comment]
I am not sure if there is anything we can do from impress.js side, I have never heard of rst2.
If there is something concrete we can do, please comment back in this issue that we might reopen it.
