### ISSUE TITLE
Removing step class when using multiple impress.js instances

### ISSUE THREAD

**Issue by jwbriney** [impress/impress.js#268]
Trying to use impress.js as a portfolio viewer with multiple projects, loading each project in using jquery .load() but I need to be able to remove the step class from any previous impress presentations.
![Screen Shot 2013-03-10 at 9 44 26 PM](https://f.cloud.github.com/assets/513653/242077/7cb1904a-89ed-11e2-9748-e8962581a9e6.png)

**Comment by FagnerMartinsBrack** [comment]
@jwbriney It is not clear what the use case is exactly. Why would you want to remove the impress classes from the `body` element?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Feel free to comment here to open up the discussion again
