### ISSUE TITLE
Bug in firefox

### ISSUE THREAD

**Issue by AliMD** [impress/impress.js#270]
I have a bug in firefox
I tested in firefox 19 in mac and win
`opacity` have bug with `data-z` in firefox !

[Demo](http://1dws.com/demo/narsis-vcard), [Bug screenshot](http://i.imgur.com/6MMH3gp.png), [Chrome screenshot](http://1.s3.envato.com/files/51279946/Narsis%20VCard%20Previews/04_preview4.jpg)

How can i fix it ?

**Comment by FagnerMartinsBrack** [comment]
Hi @AliMD , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
This seems to be an issue in Firefox that is already fixed. See also #382, #324, #443, #244.

**Comment by AliMD** [comment]
thank you, excuse me for that mail post issue
