### ISSUE TITLE
No way with dynamicaly added step

### ISSUE THREAD

**Issue by ridom** [impress/impress.js#283]
Hi everyone!

I discovered impress.js a few months ago. Thank you bartaz for this awesome tool that makes me crazy just thinking about everything is possible to do with!!

Nevertheless, I am in front of a problem: I have created dynamicaly many div reading an image folder and a json file where each div contains one image and data related. With random variables I have generated values to the attributes.
It works, all the images are displayed in the space and the generated code looks exactly the same than the "normal" one.

The issue is that only the div manually implemented in pure HTML are "stepable". I mean I can move just in the 3 steps formally created but not in the dynamic ones.

Would you have an idea about the way I should follow to make it works as well as a "normal" step?

Hope my explaination is well understandable.
Thanks!

**Comment by FagnerMartinsBrack** [comment]
A little late, but thanks everyone!

> Yes it works!

As from what I can tell from the comments this issue was solved at the time. Also, the links are not available anymore. Closing then :+1:
