### ISSUE TITLE
Attempting to create a slide only generated on a condition

### ISSUE THREAD

**Issue by ghost** [impress/impress.js#285]
I'm building a presentation which will generate a slide only upon a certain condition being true using Jquery. 

My first attempt:
By setting the display attribute to none, I thought I could have the slide not be part of the original slide deck until I run my Jquery function for it to appear.
```html
<div id="condition_slide" style="display:none;" class="step" data-x="12000" data-y="5000" data-z="2000" data-rotate="375" data-scale="1"><p>TEST</p></div>
```
```javascript
function generateSlide($ID,$isThere)
 {
   if($isThere)
   {
     $('#condition_slide').css("display","block");
   }
 }   
```
However, the presentation still transitions to a blank slide despite having the initial div styling of display:none.

Second attempt:
I have also tried not including the div in the html page within the impress div and approaching the problem as follows
```javascript
    function generateSlide($ID,$isThere)
 {
   if($isThere)
   {
     $div = '<div id="condition_slide"  class="step" data-x="12000" data-y="5000" data-z="2000" data-rotate="375" data-scale="1"><p>TEST</p></div>';
     $('#impress').children().first().append($div);

   }
 }
```
This allows the slide to appear corresponding to the condition, but it is embedded in the background of each of my slides and does not seem to be recognized as its own individual slide as part of the presentation.

Is this possible to do with impress.js or am I missing something simple? Any help or correction would be greatly appreciated.

**Comment by FagnerMartinsBrack** [comment]
Unfortunately this use case is not supported until impress.js make it possible to change it's properties dynamically. Closing in favor of #537.
