### ISSUE TITLE
How do you implement the overview

### ISSUE THREAD

**Issue by switer** [impress/impress.js#286]
Hi, I want to know how do you  implement the overview. Beacuse when i scaling the all the page in the same size instead of impress.js's overview , the element's position is diff from overivew showing position.

I make a impress editor http://switer.github.io/imper/ , the editor use drag and drop to set position. The fifth button of  left bar is to drag and drop , and the fourth button is to preview. now i hack the position , but it isn't pefect.
@bartaz Can you help me ？

**Comment by FagnerMartinsBrack** [comment]
Hi @switer , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by switer** [comment]
@FagnerMartinsBrack Thanks. I close it now.
