### ISSUE TITLE
sub menu

### ISSUE THREAD

**Issue by deanshub** [impress/impress.js#289]
# adding a menu on the buttom of the page
## in the this menu section there will be:
1. a progress bar to know what is the current slide your on and how much there is
2. right and left arrows so you can move your slides with mouse clicks
3. the menu will be added only if you add class="add-menu" to the div with the id="impress"

i have alredy made this menu :+1: 
i will add it as a pull request later today

**Comment by FagnerMartinsBrack** [comment]
Closing as stated [in the comment](https://github.com/impress/impress.js/pull/294#issuecomment-24578371):

> thanks, that's an interesting navigation

> but I'd rather see such features as 'plugins' that you add to your presentation. They don't need to be part of impress.js core library, as they can simply work using the API.
