### ISSUE TITLE
Chrome possible blink rendering engine issue?

### ISSUE THREAD

**Issue by nukeourlimo** [impress/impress.js#292]
Hey there, 

Ive just noticed a strange issue with Chrome, the site was developed and completed just before Chrome moved to the blink rendering engine and was working fine you can see the site here http://maydaylondon.com/ (to see how it should behave please check in safari or firefox)

The issue seems to be landing on the first step(which is a blank slide with no background zoomed out to provide an overview), im scratching my head trying to figure out whats going on (this was our only impress.js project and was completed early this year so im a bit rusty on the finer points of the framework)

Im seeing the issue in Chrome on Mac v27.0.1453.93 and impress.js v0.5.3

**Comment by CJohnDesign** [comment]
Any updates on this issue?
