### ISSUE TITLE
Some propositions

### ISSUE THREAD

**Issue by Announcement** [impress/impress.js#295]
Propositions
=
- __Scrolling__ within pages.
- __syntax highlighting__ 
- Sounds
- Interactivity, __subpoints__, like you press space and each point comes up one at a time.
- __Configurable hotkeys__, like show the big picture
- __Multiple__ windows (multiple screens)
- A __control panel__ (Quick editing)
- Also if you can, set it up where even making the slides is __beautiful markup__

As A Programmer
----
I know that is a lot of __MAJOR__ changes as a coder and I know they would be difficult to implement, I'm going to look at your code now, and work on it if you respond. 
Thanks for reading.

**Comment by FagnerMartinsBrack** [comment]
Sorry for the late response.

The idea of impress.js is to be a lightweight and manageable as possible. We don't want to add additional controls or many features that should be implemented in a per use-case basis. See [this comment](https://github.com/impress/impress.js/pull/294#issuecomment-24578371) for a similar example.

Also, if requesting a feature we suggest creating a dedicated issue for discussion if it was not already reported earlier.

Thanks!
