### ISSUE TITLE
performance issues when embedding processing.js sketches inside inspire.js steps

### ISSUE THREAD

**Issue by jamiewaese** [impress/impress.js#308]
I'm not sure if anybody else has tried this, but I'm happy to report that we can embed processing.js sketches inside inspire.js steps. Here is a demo you might enjoy: 

http://bar.utoronto.ca/~jwaese/zoom/zoomBrowserTest.html#/m

But here's the challenge -- since the processing sketches are all running at the same time, everything runs a lot slower than it should. Also if you open your Activity Monitor, you'll see some crazy memory requirements for the browser, and it keeps going up the longer the page is open. And these are really simple processing sketches. I fear it would be prohibitively slow if they were any more complex.

Anyhow, I'm wondering if you can suggest a technique to pull some slight of hand here, and only execute/display the processing sketches just before they should become visible? Or, do you have any other suggestions for improving the step level performance of an impress.js page? I'm hoping to use it as a framework for a set of interconnected data visualization tools, which means somewhat more complex processing sketches than my demo above!

Thanks,

Jamie

**Comment by FagnerMartinsBrack** [comment]
As from the comment above and due to the lack of feedback from the OP, I will assume the issue was fixed, if not please comment in this issue to reopen.
