### ISSUE TITLE
Removing impress at screensize (dynamically) and stopping at the end of the slideshow.

### ISSUE THREAD

**Issue by b3nhartl3y** [impress/impress.js#309]
Hi all,

I have a couple of questions I've been fighting with and wondered if you chaps would know the solutions (i'm not super hot on my jquery):

1. I'd like to remove impress (all functionality) at 768px screen size, so I can provide users with a different layout for mobile. I'd like to make this happen dynamically as the user resizes the window -  Sadly this doesn't work as I want:

```javascript
if ($(window).width() > 768) {
        impress().init();
    }
```

As this doesn't fire when the window is resized and therefor doesn't reinitiate impress when the screen is increase - and doesn't remove it when screen is decreased. 

I've tried adding and removing a class to the body at 768px then trying to remove all the CSS applied from impress but this is just getting messy. (code below) Could someone help me out?

```javascript
function checkWidth(init)
{
    /*If browser resized, check width again */
    if ($(window).width() < 768) {
        $('html').addClass('remove-impress');
    }
    else {
        if (!init) {
            $('html').removeClass('remove-impress');
        }
    }
}

$(document).ready(function() {
    checkWidth(true);

    $(window).resize(function() {
        checkWidth(false);
    });
});
```
2. I'd like my presentation to end at the last slide and not loop - I think I must be something simple - could someone point this out to me!

Many thanks, fab bit of code btw!

Ben

(updated to add the second lot of Jquery)

**Comment by FagnerMartinsBrack** [comment]
This use case will only be able to be fixed once impress.js can dynamically change it's properties. Closing in favor of #537 then.

As from the second point I have created a new issue to track too: #538.
