### ISSUE TITLE
Scroll!

### ISSUE THREAD

**Issue by fj1800** [impress/impress.js#31]
First - extremely impressed by your work! Though, the arrows might not be perfectly intuitive for everyone. Clicking neither. Adding Scroll to the ways of navigating would be a huge plus, and it shouldn't be too difficult using Scrolldeck (http://johnpolacek.github.com/scrolldeck.js/) or something like that.

**Comment by vladimirlisovets** [comment]
I spent the whole day trying to implement on web dev. diverse presentation plugins, including impress.
Impress is the best to upgrade to such purpose.
Sadly, I didn't find anything, hope someday, talented impress developers would find a way to offer such option.

**Comment by xprilion** [comment]
Hey! I have been able to implement it! I will shortly create a fork with that implemented :smiley:
