### ISSUE TITLE
it's not actually an issue

### ISSUE THREAD

**Issue by gpl4all** [impress/impress.js#317]
i must thank you for this great javascript!
still don't have idea any application that can utilize it
but i have ported the sample into Blackberry WebWorks frameworkd and successfully install the sample and running inside Blackberry Z10, it's now run in the device browser and pull from web server, but installed and run in the device as an application.
and here is the video of the sample running in Blackberry Z10:

https://plus.google.com/posts/bmYHX3hwvA8

keep up this great works! :)

**Comment by FagnerMartinsBrack** [comment]
Sorry for the late response, but thanks! :)
