### ISSUE TITLE
Forcing link-only navigation to steps

### ISSUE THREAD

**Issue by tgfisher** [impress/impress.js#325]
I have a quiz that I'm building in impress.js and I need to force the user to answer questions (each question resides on a different step) by clicking on links within the given step/question. Is there a way to prevent all other navigation methods for my question steps (i.e. arrows, spacebar, etc.)? I believe preventing those navigation options will get me the desired result.

**Comment by FagnerMartinsBrack** [comment]
> Is there a way to prevent all other navigation methods for my question steps (i.e. arrows, spacebar, etc.)?

As stated above it is impossible to disable the navigation now. We have plans to decouple impress.js from talk presentation only to general purpose and create a plugin structure. Until then unfortunately you need to comment out the code.

I have created an issue to track this issue in specific. Closing in favor of #539.

**Comment by henrikingo** [comment]
Hi @travisfisher 

I wanted to share some relevant updates from [my work](https://github.com/henrikingo/impress.js/) on a plugin api:

- The code that provides the navigation functionality is now separated into [a separate file](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/navigation). If you remove/comment the "navigation.js" entry from [build.js](https://github.com/henrikingo/impress.js/blob/myfork/build.js) file, and re-run `npm run build`. This re-creates the `js/impress.js` file without any support for the arrow/space/tab/PgUp/PgDn navigation at all.
- There's currently no way to dynamically enable and disable the keyboard navigation during a presentation (from your javascript code), but that would actually be easy to add and I'm happy to do it. Let me know if you're still interested.
- There's also a new [stop](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/stop/README.md) plugin. If you set `class="stop"` on a step, the user cannot navigate forward to the next step from there. (He can however navigate backwards to previous steps.) While this wasn't the original use case for a stop plugin, you could of course set and unset this dynamically as well.

I hope some of these recent additions can help you?
