### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by sk58** [impress/impress.js#326]
Firefox doesn't hide the overflow of the Impress presentation despite its container having overflow:hidden. Works in Chrome and Safari.

Also is there a link to the relevant polyfills to make impress.js work in IE10?

**Comment by FagnerMartinsBrack** [comment]
This was probably related to a Firefox bug that broke CSS 3D based presentations. It already happened more than once. See https://github.com/impress/impress.js/issues/324#issuecomment-22861313 and https://github.com/impress/impress.js/issues/443#issuecomment-67322992.
