### ISSUE TITLE
Impress.js not working on iOS Safari browser

### ISSUE THREAD

**Issue by ankitthakur** [impress/impress.js#332]
I have the examples and demo version on my iPhone with iOS 7 version. And the example and demo page shows warning: Please use latest Chrome/Safari version.

**Comment by Beiyi** [comment]
I test impress.js on  my iPhone5C (iOS 8.3). I remove the device black list code. And I found that it can work well on my iPhone.

**Comment by bartaz** [comment]
Thanks @Beiyi, I'm pretty sure impress.js would work good on newest devices, but it may be hard to detect if presentation will not crash the browser. Because it's just a memory issue, meaning if you create many slides in presentation (for example with big images) it may also crash on you iPhone5C.

**Comment by ahainen** [comment]
Ahoy - I'm trying this on an iPhone 6, iOS v11.2.6 15D100. I noticed as well that https://impress.js.org doesn't work in iOS Safari. i.e. It's not popping fallback mode and swiping makes the images scale/slide bizarrely. I'm fine getting impress.js to Fallback mode on mobile, but I can't seem to do that at all :/ https://ahainen.com/akroma/roadmap-2018-q2

**Comment by henrikingo** [comment]
@ahainen This is an old issue that is closed. Can you please post a new one: https://github.com/impress/impress.js/issues/new

**Comment by ahainen** [comment]
My bad, opened: https://github.com/impress/impress.js/issues/690
