### ISSUE TITLE
allow positioning of content outside of steps

### ISSUE THREAD

**Issue by zjttoefs** [impress/impress.js#337]
Apologies, if you can do this, but I didn't find a way.

I'd like to be able to place objects in random places, outside of "step" frames.
That would be frames or arrows or the like that would be good to fly past in transitions or have there as guides in the overview.

**Comment by FagnerMartinsBrack** [comment]
> Other option, to avoid navigating to those elements, would be to add these elements inside of your steps (for example step that is most close to it) and use CSS styles to position it relatively outside the step.

As from what I can tell this seems to be the best way to do what the OP wants to and therefore there is no action we can take from impress.js this time that justifies keeping this issue open.

If somebody wants to continue the discussion, just comment here that we can reopen if necessary.
