### ISSUE TITLE
Can't Mouse Click on Overview

### ISSUE THREAD

**Issue by AiMingQi** [impress/impress.js#346]
I have developed a the Cool Gadget Shop using impress and I'm having trouble with the navigation.  For some reason you can't click on the other slides from an overview step. This makes for a clunky navigation since people have to button mash to get where they want. 

Have a look at the site at http://cool-gadget-shop.com  

Any ideas would be appreciated.

**Comment by FagnerMartinsBrack** [comment]
Not sure if this was a temporary problem with some browser or if this was fixed. But today, testing [this link](http://impress.github.io/impress.js/#/overview) in Opera/Safari/Chrome on Mac, I can confirm that the steps can be clicked from the "overview" step.

Closing as not a problem.
