### ISSUE TITLE
How to make network intro? this can help a lot of people. Please help+ jpg example inside

### ISSUE THREAD

**Issue by xxx2201135** [impress/impress.js#354]
Hello, 
I have got an idea to use your perfect script for intro.
I want to have overview page 5 icons and when you click on icon you get zoom and reconnected to another site.

So basically,after first click on web-site you see "overview" with a lot of icons "logos" you can choose. And then you click and Have zoom. CLick out around picture-zoom out.
Like here on the picture

Example :
http://us.123rf.com/400wm/400/400/pashka/pashka0811/pashka081100036/3885091-set-of-vector-symbols-for-design-see-a-lot-of-high-quality-vector-logo-in-my-portfolio.jpg

What is the simplest way to do that? I have been trying also in code, but it is something I can not find out.

I have been trying to make it with some programs (Strut etc.) here but it can not make that thing I want. I need no sliders but overview as first appearance on web-site and then you can choose from images.

Been trying to make it myself with CSS but it was problem.

Dzienkuje bardzo za pomoc! Najlepszi script.Thank you for your help

**Comment by FagnerMartinsBrack** [comment]
Hi @xxx2201135 , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
