### ISSUE TITLE
How to make First slide "overview" with many icons? And if you choose one, you will be redirected to another page? 

### ISSUE THREAD

**Issue by xxx2201135** [impress/impress.js#356]
I am looking for the way how to make first slide "Overview" with many icons.
So if you click on web-site, you basically see plenty of icons (web-sites) you can click on and be redirected.

How to make 3D menu like this? 

I want to have "overview" like first thing you see when you click on web-site. And then you can choose.

Please help me out.

Thank you very much for every comment.

**Comment by FagnerMartinsBrack** [comment]
Hi @xxx2201135 , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
