### ISSUE TITLE
Is it possible to load Impress.js script tag from header? (solved)

### ISSUE THREAD

**Issue by eduardrock** [impress/impress.js#358]
Is it possible to load Impress.js script tag from header?
I don't want to put any script tag at the end of body, It doesn't look good and is a bad practice.
The problem is when I load Impress.js script tag from header, it gives me a lot of errors on console.

I've tried putting the entire Impress.js code inside $(document).onload(function(){  }); but doesn't work

**Comment by FagnerMartinsBrack** [comment]
> I don't want to put any script tag at the end of body, It doesn't look good and is a bad practice.

Put the script at the end of the body is not a bad practice, it is even encouraged. See the links below:

* https://developer.yahoo.com/performance/rules.html#js_bottom
* https://github.com/h5bp/html5-boilerplate/issues/1151#issuecomment-7355962

Also, see my comment [here](https://github.com/impress/impress.js/pull/360#issuecomment-181010672)

**Comment by FagnerMartinsBrack** [comment]
Closing as per the comment above and also due to the lack of feedback from the OP in the related PR: https://github.com/impress/impress.js/pull/360#issuecomment-192566339.
