### ISSUE TITLE
How to make First slide Overview with many slides (now is overview last slide)

### ISSUE THREAD

**Issue by xxx2201135** [impress/impress.js#359]
Please dear Bartaz, Help me, how to make first slide overview.
I have been trying it in CSS but It did not work.

Now is overview last slide but I want it conversely.

Pleas help me out. I would very appreciate it. And also donate you.
Thank you

**Comment by FagnerMartinsBrack** [comment]
Hi @xxx2201135, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
