### ISSUE TITLE
Overview mode : Slides pixelated in Chrome

### ISSUE THREAD

**Issue by ghost** [impress/impress.js#363]
Slides are getting pixelated  in chrome in overview mode.

![impress js presentation tool based on the power of css3 transforms and transitions in modern browsers by bartek szopka bartaz](https://f.cloud.github.com/assets/1628147/1947006/2c8a31e4-8037-11e3-8f79-d047c9fbb2c9.png)

In firefox it looks normal 

![impress-js-presentation-tool-based-on-the-power-of-css3-transforms-and-transitions-in-modern-browsers-by-bartek-szopka-bartaz 2014-01-18 16-50-50](https://f.cloud.github.com/assets/1628147/1947008/4b163086-8037-11e3-9ec8-e78c2124859a.png)

**Comment by FagnerMartinsBrack** [comment]
Hi @ghost, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
I see that in the OP account it is written "Deleted User", therefore I will assume this user is not tracking any of his requests anymore.

Also, opening the overview in Chrome today does not appear to be pixelated.
