### ISSUE TITLE
Control position of content on a slide?

### ISSUE THREAD

**Issue by amandabee** [impress/impress.js#370]
Tried asking this on Stack Exchange but I haven't gotten many views and definitely no answers:

http://stackoverflow.com/questions/22100898/smaller-slide-margins-in-impress-js

I have a longish block of `<pre>`formatted text that would fit on a slide just fine if I could use the full viewport, but I can't even find a demo that includes a slide that does. 

![so_far_right](https://f.cloud.github.com/assets/150791/2299087/2efed474-a0c7-11e3-9078-34ca1aeff8d8.png)
 
I'm looking for suggestions for CSS that will embiggen the div for this slide so it uses the full screen width or at least starts at the far left. Any suggestions?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
