### ISSUE TITLE
Event "stepleave", How can I get the ID of the next step before arriving there?

### ISSUE THREAD

**Issue by eduardrock** [impress/impress.js#375]
I'm writing a plugin for assigning a document.body backgroun color for every slide.
When I use the event impress:stepleave, I need to know the ID of the next step where is moving in the moment, because I need to start a CSS-transform with transition for changing the background color according to the target step color.

**Comment by FagnerMartinsBrack** [comment]
Refer to #206 for an implementation example.

**Comment by FagnerMartinsBrack** [comment]
Hi @eduardrock, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again
