### ISSUE TITLE
Font-size as "px" or "em"? What is better for Impress.js?

### ISSUE THREAD

**Issue by eduardrock** [impress/impress.js#378]
If I want to make a presentation with Impress.js and I want the text size look equal on all the devices and avoid line break on some words.

Is it better to use "px" or "em" for the font-size?

**Comment by FagnerMartinsBrack** [comment]
Hi @eduardrock, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again

Also, this question seems to have been answered already.
