### ISSUE TITLE
inline editing width ckeditor 4.x 

### ISSUE THREAD

**Issue by flocondetoile** [impress/impress.js#380]
Hi,

Really great work this impress.js framework.

I'm trying to permit inline editing slide with ckeditor 4.x.
I succeed to get the ckeditor toolbar when i click in the slide, but I can't use the ckeditor  toolbar because it seems that the content of the slide is on top of toolbar (where as i checked all elements z-index property).

Have you got an idea to make the ckeditor toolbar accessible on an impress.js presentation ?

Thank you

**Comment by FagnerMartinsBrack** [comment]
I will assume from the last comment that this issue is fixed.
