### ISSUE TITLE
doesn´t fit on an iPad screen

### ISSUE THREAD

**Issue by adrian-martin86** [impress/impress.js#383]
I was testing my impress.js presentation in different devices and it works in almost everything, the framework can adapt the presentation with a responsive design behavior in different resolution, but when I tried into an iPad (safari, chrome, dolhpin) it does not adapt to the screen´s resolution, even when I touched the screen to pass to another page it does not work fine. What can I do to solve this iPad´s issue ??

**Comment by FagnerMartinsBrack** [comment]
Closing as from [this comment](https://github.com/impress/impress.js/issues/333#issuecomment-204729226).

Basically impress.js does not support mobile devices as it currently stands. We need to review this, see also #282.
