### ISSUE TITLE
playing videos with stepenter

### ISSUE THREAD

**Issue by vitorcarvalhoml** [impress/impress.js#385]
Hi! I'm playing html videos with stepenter event. Looks very good. But the slide will run all day in loop.
After sometime, I have got a delay, between the step enter and the video starting.
I read about a delay that is applicable in step on file impress.js. But I didn't see where I can use it here or if this is the solution to my problem.

This function I use to start video.
    
```javascript
function startVideo() {
	document.addEventListener('impress:stepenter', function(e) {
		var slideContent = e.target.getAttribute('data-content');
		if (slideContent == 'video') {
			var videoPlayer = document.getElementsByClassName('active')[0].firstElementChild;
			videoPlayer.play();
		};
	});
}
```
And this one I use to get step duration.

```javascript
function setSlideDuration() {
	document.addEventListener('impress:stepenter', function(e) {
		if (typeof timing !== 'undefined') clearInterval(timing);
		var duration = (e.target.getAttribute('data-content-duration') ? e.target.getAttribute('data-content-duration') : 2000); 
		timing = setInterval(slider.next, duration);
	});
}
```

How can I prevent this delay to occur.

**Comment by FagnerMartinsBrack** [comment]
Hi @vitorcarvalhoml , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by vitorcarvalhoml** [comment]
Hi @FagnerMartinsBrack great to hear! Good news to the project. But I'm no longer looking into this. So we can close it!
