### ISSUE TITLE
Auto play Remove

### ISSUE THREAD

**Issue by chokri** [impress/impress.js#390]
I'm about building an Impress JS presentation, but I modified some things on impress.js. I would talk about them here,
I created an Interractive presentation so I have to delete the spacebar hit to move the next slide, I use the slidebar to run a javascript animation to each slide (gallery, charts, video, ...) but I see that impress init() don't show me {options} to stop the autorunning of the presentation and set animation's duration to each slides.

**Comment by FagnerMartinsBrack** [comment]
Hi @chokri , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Feel free to comment here to open up the discussion again
