### ISSUE TITLE
Clipping on iPad

### ISSUE THREAD

**Issue by shaase** [impress/impress.js#391]
Great library! I am moving around a rather large image that I've zoomed into. Everything works well until I zoom out and there's some clipping issues on iPad. Parts of the image are gone for a few quick moments after the transition is done, then they return. Have you encountered this and do you have any thoughts on managing this? Thanks!

**Comment by FagnerMartinsBrack** [comment]
Hi @shaase , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by shaase** [comment]
Hey @FagnerMartinsBrack , the recent developments for this project are very exciting! I haven't used the library in well over a year, so I'm going to close the issue. If I start to actively use it again and come across the issue, I'll open another issue.

**Comment by FagnerMartinsBrack** [comment]
@shaase Glad to know you liked it! Things are going slow, but at least they are going :)
