### ISSUE TITLE
Auto-sliding

### ISSUE THREAD

**Issue by karanganesan** [impress/impress.js#392]
Can any one contribute to bartaz in developing the Auto-sliding feature to make impress.js the ultimate and complete presentation kit please ????
I got this idea.............................

**Comment by FagnerMartinsBrack** [comment]
Hi @karanganesan , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Feel free to comment here to open up the discussion again
