### ISSUE TITLE
How to make the image fit the size of parent <div> with "step" class?

### ISSUE THREAD

**Issue by chenweiyj** [impress/impress.js#394]
I have a big jpeg image to show in `impress`. When I tried to define following css based on `impress-demo.css`, it still shows part of my images.

```
.step img {
    width: 20%;
    height: 20%;
}
```

I want a way to resize and show the whole image in the `div` container. Could anyone how to do it? Thank you!

**Comment by sylvaintrias** [comment]
Hi !

I have the same problem here, but when I add max-width, my image disappears.

`<body>
    <div id="impress">
        <div class="step" data-x="-1833" data-y="-1567" data-scale="1">
            <img width="1869" height="1189" src="images/1-PO.png"/>
        </div>
        <div class="step" data-x="0" data-y="-3244" data-scale="1">
            <img width="2151" height="1412" src="images/2-SH.png"/>
        </div>
    </div>
</body>`

Actually the view by default scales so that my image fills the screen. Instead I want it to FIT the screen so I can see it entirely.

Thanks
