### ISSUE TITLE
How can I apply 'data-x', 'data-y', 'data-rotate', and so on to <img> tags?

### ISSUE THREAD

**Issue by chenweiyj** [impress/impress.js#395]
I want to show many images in one `step`, which do around a text title of the step. It looks like multiple images pin to a wall with irregular position. Although it can be realized by using many steps each step contains one image, it is not what I want, because I only want to show the photo wall one time. 

So does anyone know how to solve it? Thank you!

**Comment by FagnerMartinsBrack** [comment]
Hi @chenweiyj , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Feel free to comment here to open up the discussion again
