### ISSUE TITLE
`goto(id)` in `impress:stepleave` event has no effect

### ISSUE THREAD

**Issue by chenweiyj** [impress/impress.js#397]
I have added an event to a step with `#prep` id. When we leave this step, it will jump to another step but not the next, e.g. the `#title`. The following is my piece of code, but it does not work.
```
<script>
      var prep = document.querySelector("#prep");
      prep.addEventListener("impress:stepleave", function () {
        impress().goto("title");
      });
 </script>
```

Does anyone know this problem? thank you.

**Comment by ax3l** [comment]
@chenweiyj did you find a solution to that?

**Comment by FagnerMartinsBrack** [comment]
Hi @chenweiyj , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Feel free to comment here to open up the discussion again
