### ISSUE TITLE
我写了一个代码详解，帮助大家更好的理解代码

### ISSUE THREAD

**Issue by numbbbbb** [impress/impress.js#398]
I have written an article in chinese to explain the source code.
Even if this source code is simple and has many comments, you know in China many people cannot understand English. 
So I wrote the article in order to help these people understand impress.js.

我写了一篇文章来详细解释impress.js的代码，[点我查看](http://www.cnblogs.com/numbbbbb/p/3756140.html)。
如果有什么错误或者建议都欢迎大家提出~

**Comment by Leonard-Li777** [comment]
辛苦了！谢谢
