### ISSUE TITLE
How can I auto increment the data-y position using jQuery?

### ISSUE THREAD

**Issue by stacigh** [impress/impress.js#400]
I'm trying to move each slide on the y-axis by 900px every time. I wrote a jQ function that works in the code (I can see the values added in the source) but the slides are stacked on top of eachother instead of being in the right place. Here's the jQuery code I'm using:

```
	var counter = 0;
	$('.slide').each(function(){
		var posY = counter * 900;
		$(this).attr("data-y", posY);
		counter++;
	});
```

**Comment by FagnerMartinsBrack** [comment]
Hi @stacigh , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
