### ISSUE TITLE
Trigger CSS animation when slide open

### ISSUE THREAD

**Issue by eudennis** [impress/impress.js#401]
How could I make an animation to trigger when the slide get focus? This should be fun, even more impressive using CSS libraries like Animate.css (https://github.com/daneden/animate.css) and Magic (https://github.com/miniMAC/magic).

Any ideas? :)

**Comment by hamidrezabstn** [comment]
hi 
you can easly solve this problem in fact @bartaz snippet is ok but should know that you most add animated class plus your desire animation class! with this trick u can use all animate.css stunning animations in impress.js ;)

example for shake animation:

$('#mystep').on('impress:stepenter', function(){
     var step = $(this);
     step.find('.button').addClass('animate shake');
});

//this remove section is for when you want to repeat animation each time user visits that step
$('#mystep').on('impress:stepleave', function(){
     var step = $(this);
     step.find('.button').removeClass('animate shake');
});

BTW: i write some snnipet that may help you even better ;)

 $( document ).ready(function() {
            function animation(stepId,animateClass){
                $('#'+stepId+'.animation').on('impress:stepenter', function(){
                     var step = $(this);
                     step.find('i.fa').addClass('animated '+animateClass);
                });
                
                $('#'+stepId+'.animation').on('impress:stepleave', function(){
                     var step = $(this);
                     step.find('i.fa').removeClass('animated '+animateClass);
                });
            };
                animation('contact','shake');
                
        
        
        });

have Fun

**Comment by FagnerMartinsBrack** [comment]
I guess the problem was fixed given the comments above. If not please let us know so that we can continue the discussion.
