### ISSUE TITLE
Scaling out and back in from one slide to another

### ISSUE THREAD

**Issue by WonderboyPark** [impress/impress.js#403]
When going from one slide to another, does anybody know how to scale out from first slide, have the presentation move to second slide, then scale back in? 

Example: Slide one and two would have scale 1 but at the center point of the transition the scale would be 2

**Comment by FagnerMartinsBrack** [comment]
Hi @WonderboyPark  and @inlandyears , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
