### ISSUE TITLE
Reload "data"

### ISSUE THREAD

**Issue by superandrew** [impress/impress.js#407]
Is it possible to tell impress to reload the presentation supposing that some javascript altered one of the div's attributes such as data-x, data-y etc?

I've tried to call `impress().init()` again to no avail. It would be a really nice improvement!

@bartaz If it's not there as I suspect, could you point me in the right direction to write it? I was trying to bind it to angular.js in some way, I suppose it would be very nice :)

Thanks

**Comment by FagnerMartinsBrack** [comment]
Closing if favor of #537.
