### ISSUE TITLE
destroying impress.js

### ISSUE THREAD

**Issue by devidcillo** [impress/impress.js#409]
Hi all,

What would be the easiest way to destroy the impress.js instance? My website will use a presentation as an introduction but I would like it to disappear once it's done the job. 

Thanks

**Comment by FagnerMartinsBrack** [comment]
It is actually feasible to create a `destroy` functionality, although it is not easy. We should keep track of all the previous data in the elements in order to rollback the changes to the previous state before impress.js was initialized in the page.

**Comment by henrikingo** [comment]
1.0.0-beta1 now suppports `impress().tear()`
