### ISSUE TITLE
Wordpress integration with Impress help!!!

### ISSUE THREAD

**Issue by ksmith25** [impress/impress.js#411]
Hello! Impress is amazing, and i can not wait to use it! However, I am having trouble getting it to work in worpress. 

i have downloaded the zip file on here and tried to upload it through the plugins page, but it says install failed. I cant really seem to find specific instructions to get this to work, and i am learning as i go, so if it is something obvious please forgive me. I also tried to upload the files through FTP but nothing appears on wordpress admin or anywhere. 

my question - how do i get the files on to wordpress, then how do i make a presentation to put into worpress? I am able to make a presentation and view it in chrome just fine when i open the file, but cant get it into WP.  Next question, once the files are in WP, do i just go to a New Page and enter my presentation code in the content area? 

sorry, i am really confused about this, and i have been trying to find a solution for the past 4 hours. It is one of those things where once i get it installed right the rest will be a breeze lol.... the html coding for the presentation will not be a problem. I just need to start!

any help appreciated

**Comment by FagnerMartinsBrack** [comment]
Hi @ksmith25 , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
