### ISSUE TITLE
Feature request - escape button defaults to overview

### ISSUE THREAD

**Issue by yejodido** [impress/impress.js#413]
Thought this would be great; regardless
Of where the starting slide is, pressing escape brings the view to #overview

**Comment by FagnerMartinsBrack** [comment]
Unfortunately that is not possible. The overview is not part of impress.js API, it is just an empty step that is positioned in a way that shows all the content of the other steps. You can implement this feature locally though.

Related to https://github.com/impress/impress.js/pull/399.
