### ISSUE TITLE
mouse coordinates 

### ISSUE THREAD

**Issue by blacksburg98** [impress/impress.js#421]
Hi,
  I'm using impress.js and dygraphs.js together. I got a problem that the mouse coordinate shift to left. You can see an example at
 http://store-demo.appspot.com/tutorial/impress.html

The normal behavior is like
http://store-demo.appspot.com/tutorial/tutorial4.html

  Tsung-Han Yang

**Comment by FagnerMartinsBrack** [comment]
Hi @blacksburg98 , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

PS: The links doesn't seems to be working anymore.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
