### ISSUE TITLE
Impress.js, parallax.js and SmoothScroll

### ISSUE THREAD

**Issue by Emyleen** [impress/impress.js#423]
Hello,

I work on a website with impress.js and I don't understand why I have interactions with parallax.js and SmoothScroll. Backgrounds of parallax are 50% on the left and I can't center them. And the smoothScroll make my page disappear. 
Need help please :o Thank you!

**Comment by FagnerMartinsBrack** [comment]
Hi @Emyleen , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
