### ISSUE TITLE
Add option to disable slides

### ISSUE THREAD

**Issue by mhils** [impress/impress.js#428]
Hi @bartaz,

Thanks for your excellent library - it's a lot of fun to use. I developed a fairly small patch which allows me to mark slides as disabled so that they get skipped when navigating via keyboard. This has two particular use-cases:
1. Placing objects in the 3d space which are not directly part of an individual slide.
2. Quickly excluding slides (obviously)

This change only affects the `next()` and `prev()` functions in impress.js. Would you be interested in such an addition? I'd be happy to remove my underscore/lodash dependency and send a PR if you feel that this would be useful for everyone.

Cheers,
Max

**Comment by FagnerMartinsBrack** [comment]
> Placing objects in the 3d space which are not directly part of an individual slide.

Sorry, but I don't understand this use case, why would someone want to place an object in the 3D space that is not a part of the individual slide? Is disabling removing the step? Can you please elaborate on why that would be useful? Maybe with a visual real world example or something like that?

Also, if this is related to #290, wouldn't "skip" or "static" be a better naming?

Thanks!

**Comment by mhils** [comment]
> Sorry, but I don't understand this use case, why would someone want to place an object in the 3D space that is not a part of the individual slide?

My primary use case is having backup slides in the overview at the end. They won't be in the presentation when I navigate with arrow keys/presenter, but I can click on them in the overview at the end (or during the presentation). A small code example is given in #429.

I'm open to renaming this to skip if you feel that works better.

**Comment by FagnerMartinsBrack** [comment]
> My primary use case is having backup slides in the overview at the end.

I will try to elaborate the questions and also clarify why I am asking all this:

* Why do you want backup slides exactly, what do you want to achieve in your presentation that can't be done without this feature?
* For your use case, can't you position a menu with links that goes to specific steps? If not, why?

My point is that I am trying to get to the "why" of this in a user perspective. The user requirements.

> A small code example is given in #429 

When I mean by example I mean a visual real world example where this feature is being used. Preferentially not links, but a demonstrable gif (that can stay documented in this issue forever, because links can become obsolete).

Thank you!

**Comment by mhils** [comment]
> For your use case, can't you position a menu with links that goes to specific steps? If not, why?

That works of course, but I'd like to have my HTML logically grouped. 
Also, it's very convenient to just disable a few slides when shortening a presentation.

**Comment by FagnerMartinsBrack** [comment]
> it's very convenient to just disable a few slides when shortening a presentation

You can also comment them, there is no benefit in creating a new API that should be documented and supported for everyone from now on for this specific reason.

> but I'd like to have my HTML logically grouped

Can you please show an example of the benefits of logically grouped markup?

**Comment by henrikingo** [comment]
You can now use `class="skip"` to skip a slide during next/prev navigation.
