### ISSUE TITLE
Shift+Tab for going to previous step

### ISSUE THREAD

**Issue by bartvanderwal** [impress/impress.js#446]
Checked out impress.js code+comments today, and did a change in the process, but I seem to have done the same thing as mentioned issue #260 and #156 and #149 :smile:. 

These all followed up on your own (@bartaz) comment: 
> And yes, I know that for the sake of consistency I should add [shift+tab] as opposite action...

The issue/pull requests are all from one or more years ago, but none of them have made it for apparently different reasons. So I stumbled onto the same issue again.

I now made a clean addition on the latest version, so can you accept this pull request?

Anyway, thanks for the great work, I'm impressed :wink:, can't wait to really get my hands dirty.

**Comment by FagnerMartinsBrack** [comment]
I managed to implement this in a fork: https://github.com/bartaz/impress.js/issues/435#issuecomment-62306959 (See "shift + tab" section)

**Comment by FagnerMartinsBrack** [comment]
PR #550. Any review is appreciated.
