### ISSUE TITLE
Insert <iframe> on slides.com

### ISSUE THREAD

**Issue by Anish-Agnihotri** [impress/impress.js#450]
When I try to insert a <iframe> on slides.com using impress.js frame working it happens to not work and show me a dark X? Please help!

**Comment by Pierstoval** [comment]
Please show your html code for we can see better where the problem is

**Comment by FagnerMartinsBrack** [comment]
Hi @Anish-Agnihotri , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
