### ISSUE TITLE
A link between the slides

### ISSUE THREAD

**Issue by Marecages** [impress/impress.js#460]
Hello everybody,

I try to put a visual link (a line) between my (circular) slides with impress.js via the stylesheet. (#) 
Any idea to do that?
(#) I would like a diaporama like Pearltrees (http://fr.locita.com/wp-content/uploads/2013/03/pearltrees-nouvelle-version-immersive.png)

Thank you in advance

**Comment by bartaz** [comment]
I think the easiest way would be to make a line part of one of connected steps (as a child element or pseudo element in CSS). And the line itself could be a long div with no height and a border as a line.

A quick example to start with may look like this: http://dabblet.com/gist/8d09721284ca89e98129

You can also use CSS transform rotate to give the line some angle like on a diaporama you linked.

Hope it helps. Have fun!

**Comment by Marecages** [comment]
Thanks a lot for that answer !
