### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by tobegit3hub** [impress/impress.js#462]
Using `impress.js` is easy and I can download the source code to edit my presentation. But I have to go to github and search `impress.js` every time I want to make a presentation. I find out the better way to download the code with `bower install impress.js`.

It's much easier than `git clone https://github.com/bartaz/Impress.js` or click the button and uncompress the file. It would be great to add these in readme so that everyone knows how to `use the source` :smiley:

**Comment by FagnerMartinsBrack** [comment]
Hi @tobegit3hub, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

I edited the title for better SEO, this request seems to be related to bower support.

**Comment by FagnerMartinsBrack** [comment]
I edited the title for better SEO, this request seems to be related to bower support.

I guess we don't need to wait for feedback to close this issue, since the project already supports bower, see https://github.com/impress/impress.js/blob/8e4888385355059d60b608a19245bd300752bb86/bower.json

**Comment by tobegit3hub** [comment]
Great. Thanks @FagnerMartinsBrack :smiley:
