### ISSUE TITLE
A background and transitions moving in the same time

### ISSUE THREAD

**Issue by Johnoob** [impress/impress.js#464]
Hello,
I would like to apologize in advance for my poor english ...
I want my background to move just like every .step or .slide, it will allow me to design my composition with the help of a background-image, I hope you understand what I'm trying to say

Put a background-image to the body make the image just static,
so I tried to create an id="impress", and give it a background image however it doesn't work, Have you got an idea ? Thank's

**Comment by FagnerMartinsBrack** [comment]
The step element is absolute positioned, so if u want an image to be used in the background you have to adjust the width/height of the step element to fit the whole screen.

**Comment by FagnerMartinsBrack** [comment]
Hi @Johnoob , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
