### ISSUE TITLE
Licensing.

### ISSUE THREAD

**Issue by darkwiz666** [impress/impress.js#468]
I don't see any documents or posts referencing to any licences applied to the project. I don't want to go getting myself into trouble using it as a base for a commercial product if it's not allowed...

**Comment by bartaz** [comment]
LICENSE

Copyright 2011-2012 Bartek Szopka

Released under the MIT or GPL (version 2 or later) Licenses.

It's mentioned in the end of readme file. But I should probably add LICENCE file to make it clear.
https://github.com/bartaz/impress.js#license

**Comment by darkwiz666** [comment]
Yeah, I read through it but I didn't see it. It's usually at the beginning so.

**Comment by tvanollefen** [comment]
I added a license file in a pull request if you'd like to add it to the main repo!

**Comment by FagnerMartinsBrack** [comment]
This is fixed as from https://github.com/impress/impress.js/pull/511
