### ISSUE TITLE
IE perspective setting bug

### ISSUE THREAD

**Issue by bartuer** [impress/impress.js#476]
In IE, transform : perspective(2000px) doesn't work, need set perspective on #impress directly, like
-ms-perspective : 2000px
![no_perspective](https://cloud.githubusercontent.com/assets/25855/7703762/b2313a9a-fe6c-11e4-9399-dff15518ed0e.PNG)
![has_perspective](https://cloud.githubusercontent.com/assets/25855/7703771/bc9403b4-fe6c-11e4-8256-1bde42bc104f.PNG)

please fix it

**Comment by bartaz** [comment]
Thanks for reporting.

So you mean that `perspective` is not supported as a transform function in IE but works fine as separate value?

**Comment by bartuer** [comment]
exactly.

**Comment by jdalton** [comment]
Hey @bartuer!

Can you check out the PR over at #476 to see if this resolves the problem.

**Comment by jdalton** [comment]
Erm over at #594.

**Comment by jdalton** [comment]
Looks like it does 🎉

**Comment by jdalton** [comment]
Moved to #594.
