### ISSUE TITLE
Microsoft Build 2015 Keynotes using ImpressJs

### ISSUE THREAD

**Issue by rSafari** [impress/impress.js#477]
Hello folks ,

here is my slides for microsoft build 2015 which im presenting tomorrow .
it built using impressjs and particlejs .

feel free to use it and make your own , of course nothing really special about that . 

source : https://github.com/rSafari/st24
preview : http://rsafari.github.io/st24/

**Comment by bartaz** [comment]
Thanks, you could add it to wiki: https://github.com/impress/impress.js/wiki/Examples-and-demos#presentations
