### ISSUE TITLE
Feature request: relative data-* values

### ISSUE THREAD

**Issue by bendavis78** [impress/impress.js#478]
I think it'd be nice to be able to position slides relative to the previous one. 

So, for example, instead of this:

``` html
<div class="step slide" data-x="0">Slide A</div>
<div class="step slide" data-x="1000">Slide B</div>
<div class="step slide" data-x="2000">Slide C</div>
<div class="step slide" data-x="3000">Slide D</div>
```

We would have this:

``` html
<div class="step slide" data-x="0">Slide A</div>
<div class="step slide" data-x="+1000">Slide B</div>
<div class="step slide" data-x="+1000">Slide C</div>
<div class="step slide" data-x="+1000">Slide D</div>
```

That way, if I needed to insert a slide somewhere in there, it doesn't mess up the overall flow.

**Comment by henrikingo** [comment]
Hi @bendavis78 

There are a couple pull requests that implement this in various ways. I have one here: https://github.com/henrikingo/impress.js/

**Comment by jacekkopecky** [comment]
I too have various extensions including relative positioning at https://github.com/jacekkopecky/impress.js

**Comment by henrikingo** [comment]
@jacekkopecky Wow that's an impressive number of commits!

We need to get all this stuff into one repo. I'll try to make progress with @bartaz tomorrow or next week, see if we can poke this forward a bit.

**Comment by jacekkopecky** [comment]
And it's not all - I still have some things I've used but haven't pushed yet.

I actually just thought about starting over, refactoring impress to better suit my needs; but I'll still push everything I've done and used to my fork and I'll be very happy if any of it is useful in the main repository. Let me know and I can prepare PRs.

**Comment by henrikingo** [comment]
Oops, I've completely forgot to come back to this thread.

@jacekkopecky Some months ago already, I've added [a Relative Positioning Plugin](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/rel/README.md) to my for of impress.js, where I implemented a plugin API based on bartaz' guidance. Please have a look and let me know what you think.

[This demo presentation](http://henrikingo.github.io/impress.js/examples/classic-slides/) uses the relative positioning data- attributes.

**Comment by henrikingo** [comment]
The relative positioning plugin is now part of impress.js master, as of 1.0.0-beta1
