### ISSUE TITLE
Presentation demo no longer existing

### ISSUE THREAD

**Issue by alebaffa** [impress/impress.js#491]
Hi, 
just wanted to tell you that in the demo section the following presentations give "404 page error" :
- "Gauge conditions and blackhole stability by Kartik Prabhu" gives a 404 error page. I think the author has removed it.
- "Speeding Up Drupal by Evan Willhite @evanmwillhite"
- "How to build WordPress theme and plugin by Bernard Latanowicz"

The followings have wrong link:
- Rukun Iman | Jeniv by Jefry Nivella - A cube presentation.
- Toward the development of a web literacy map by Doug Belshaw

I think you can remove all these links from the list of demos.

Cheers,
Alessandro

**Comment by alebaffa** [comment]
Also "Speeding Up Drupal by Evan Willhite @evanmwillhite". 404 error page.

**Comment by alebaffa** [comment]
Just tell me if you prefer a pull request to remove them.

**Comment by electricthread** [comment]
I went ahead and fixed the Speeding up Drupal link http://www.electricthread.com/speed-drupal. Thanks for the heads-up @alebaffa

**Comment by bartaz** [comment]
@alebaffa if you are taking about the links on wiki: https://github.com/impress/impress.js/wiki/Examples-and-demos - there is no need for pull request, it should be editable by anyone, so go ahead and remove links that are dead.

Thanks for checking it out!

**Comment by alebaffa** [comment]
ok cool! :+1:
