### ISSUE TITLE
Setting impress.js to fill up the entire screen?

### ISSUE THREAD

**Issue by dsignr** [impress/impress.js#493]
Hi, I'm right now playing with impress.js and first of all I must say thank you very much for this wonderful library :) :+1: !

I noticed that all examples included and all demos of impress.js I've seen so far fill up only 80% of the screen size. Is it possible to make this 100%? I noticed that the `#impress` div sets up the scale on the fly and that's why perhaps it's not able to fill up the entire screen. Could you kindly please advise on how to make impress.js fill up the entire screen? Thanks!

**Comment by bartaz** [comment]
There is couple of settings that manages scaling of whole impress.js presentation:
https://github.com/impress/impress.js/blob/master/js/impress.js#L201-L204

In short - width and height are treated as default size of screen/presentation. This means impress.js assumes screen has this size and it tries to scale presentation so fit this size.

Also max scale manages how impress.js scales this presentation. Default value of 1 means that slides will not get bigger than their original size, even if the screen is bigger.

So to answer your question.
First of all, try to configure width/height and adjust them to your screen size.
Or make maxScale bigger to allow slides being scaled up above original size to fit bigger screens. But it may cause slides to look blurry.

**Comment by dsignr** [comment]
Hey @bartaz !

Thanks for the quick response! I managed to get it working by overriding the value for scale in this line: `
https://github.com/impress/impress.js/blob/master/js/impress.js#L154

I set `scale = 1` and the presentation is scaled to max. I hope this doesn't mess up something else later, though. 

Thanks!

**Comment by bartaz** [comment]
It should work as long as you don't change the screen size.

Because overriding scale to fixed value means that impress.js will not adjust presentation size to screen size.

**Comment by dsignr** [comment]
@bartaz I tried setting the screen size values myself in the config, but they had no effect. So I had to resort to manually over-riding the scale to 1. Perhaps, I should just call the function that resizes the slides using modernizr or something. Thanks a lot for your quick response :)

**Comment by CJohnDesign** [comment]
Thanks @bartaz 👊🏼

Updated link to the width/height defaults:  https://github.com/impress/impress.js/blob/80ffff0e8f603a82d9abb6eb51647732c2c8563e/js/impress.js#L170-L172

**Comment by tdotholla** [comment]
for anyone that finds it, this is the easiest way: 
#impress {
  transform: scale(1) !important;
}

**Comment by henrikingo** [comment]
Hi all. Note that the screen size, or "target screen size" values and the scaling configuration are settable in HTML. I added documentation for it now: https://github.com/impress/impress.js/blob/master/DOCUMENTATION.md#root-element
