### ISSUE TITLE
Authoring tool discussion

### ISSUE THREAD

**Issue by iangilman** [impress/impress.js#5]
I love it!

Perhaps out of the scope of this library, but I figured I'd file it here nonetheless: in order for this to be useful for more than a few people, you need some sort of authoring tool for these kinds of presentations, such as what Prezi has, or my own Infinite Canvas tool from several years ago:

http://infinitecanvas.jgate.de/create?name=Brad%27s%20Somber%20Mood

Any plans to do something like that, or are you leaving it to the community?

**Comment by Toub** [comment]
Here is a suggestion about how to accept new contributers.

First ask volunteers to review existing pull requests and comment them. Then, review some of the reviews...

Finally, you can integrate a few first contributers (who submitted good quality PR or good review).

Thanks for opening the governance of this project!

**Comment by dalareo** [comment]
Have you noticed about this??
https://github.com/regebro/hovercraft
It seems quite interesting!!

**Comment by FagnerMartinsBrack** [comment]
Dude I would love so much an editor like medium, using the presentation itself as the editor tool. I am up to create something MIT in the future if there's enough folks to backup (and if impress.js get on its tracks xD).

**Comment by szaghi** [comment]
Hi all, I see the [wiki page](https://github.com/impress/impress.js/wiki/Examples-and-demos#authoring-tools) listing some authoring tools. I would like to add [MaTiSSe](https://github.com/szaghi/MaTiSSe) to the list, it being a mature authoring tool tailored for scientific contents (replacing LaTeX beamer introducing all the fancy of impress.js within the simplicity of markdown). Is it posdible to add it to the list?

**Comment by FagnerMartinsBrack** [comment]
X-Ref #362.

There the OP says it is hard having to manually edit the step attributes, so it was proposed a tool that does that automatically. This is totally something that an authoring tool should provide.

**Comment by henrikingo** [comment]
Hi all

Just a few notes on recent progress on this very old thread.

In a separate repo from impress.js, I have also created a new editor [Impressionist](https://github.com/henrikingo/impressionist). It's still a work in progress, but you can at least create slides, position them in 3D and save the presentation (barely). I intend to move this into the impress project once I finish cleaning up the state of impress.js itself.

Many editors presented here seem to be web applications that run on a server and you need to use them over the internet. Impressionist otoh is based on Electron, so you install and run it as a desktop app, and it saves files on your desktop as well. There's a video demo in the README if you want to see more.

(To clarify: There's no relation to the other Impressionist editor that is mentioned in this thread. It seems to no longer be actively developed, and URL stopped working?)

Btw, as a reminder in case someone didn't realize it yet, [the wiki has a list of impress.js editors](https://github.com/impress/impress.js/wiki/Examples-and-demos#authoring-tools)


I also wanted to mention some other new features in impress.js itself, that make authoring presentations easier:

* You can now [use relative positioning on steps](https://github.com/impress/impress.js/blob/master/src/plugins/rel/README.md). (Similar to e.g. Hovercraft, but now directly in HTML.)
* You can [use Markdown to write the slide contents](http://impress.github.io/impress.js/examples/markdown/#/markdown) (again, directly in the html file itself. Markdown.js is used to transform it to HTML).
* For scientific use, you might be interested in the [Mathjax.js integration](http://impress.github.io/impress.js/examples/classic-slides/#/step-11) that allows to use Latex, Asciimath and MathML in impress.js presentations.
