### ISSUE TITLE
IE10 not supported anymore

### ISSUE THREAD

**Issue by mchendriks** [impress/impress.js#506]
In the previous version Chrome and FireFox were not working as expected (no prezi effect), but IE10 en Safari did.

In this version the IE10 version is not supported anymore, but FF and Chrome are?

Would be nice if impress would be cross-platform.

**Comment by bartaz** [comment]
I'm not sure which versions you mean - nothing major changed in years in impress.js.
It's possible that browsers updated/changed some of their implementations making impress.js supported in more browsers.

IE10 was never supported out of the box as is didn't implement `classList` or `dataset` attributes from HTML5. I don't know if it changed, but probably didn't.

**Comment by mchendriks** [comment]
It's actually the jmpress.js, the jquery plugin, a working example in IE10 you can find on:

on http://new.digirent.nl/examples/impress/

But not working om FF and Chrome.
Your current version is working in Chrome and FF but not in IE.

**Comment by bartaz** [comment]
jmpress is completely separated project, rewritten from scratch as far as I know, so it has simply other requirements and browser support. 

So for help with browser support for that I suggest consulting their repository: https://github.com/jmpressjs/jmpress.js

**Comment by FagnerMartinsBrack** [comment]
Closing because it was probably reported in the wrong repo.
