### ISSUE TITLE
Rotate: Find shortest rotation

### ISSUE THREAD

**Issue by peternerlich** [impress/impress.js#508]
I played with the idea to base one of my slides on spirals. The only problem: I have to calculate a lot of 360s to have a proper camera movement. I thought about somehow, after each step transition, normalizing the rotations back to [0,359] and finding the shortest rotation between slides. There would have to be something to suppress the animation when resetting.
I know I would be faster to shut up and plan my slides properly before hard-coding them, but that's not the point of development, is it? ;-)

**Comment by FagnerMartinsBrack** [comment]
Hi @peternerlich , in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older issues like this one to see if [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm) is still interested in keep it going.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again

**Comment by peternerlich** [comment]
Sorry, read the notice, but forgot about it again.
I am generally still interested in a solution, but am currently not actively working with **impress.js**. So I don't know if reopening is the right thing here.

**Comment by FagnerMartinsBrack** [comment]
@peternerlich Thanks for the response!

> I am generally still interested in a solution

Nice to hear that. The problem is that I don't understand yet what is the issue xD

Can you please elaborate what is the issue in details, maybe with some LICECap gifs for visualization and small code snippets?

If the issue is clear, we might save it for implementation in the future. No need to work with impress (although we encourage you to :D).
