### ISSUE TITLE
Initializing first step at page loading

### ISSUE THREAD

**Issue by vladimirlisovets** [impress/impress.js#518]
Hello, 

I've been implementing impress.js in a web page.

While trying to apply anchors in another context rather than impress.js plugin (beside of impress.js), I realized that the plugin redirects to the first step when the page loads. 

I tried to find the part of the code wich does that, but without any success.

Even finding interesting functions which may have lead me to find what I wanted (goto() ,etc.)

If somebody can give me any indication which may me help to block this function or change under my needs - I'd be eternally thankful !

Thanks in advance,
All the best, Vlad.

**Comment by FagnerMartinsBrack** [comment]
Can you please post a working example with the steps to reproduce the problem? That will make it easy for us to look into.

**Comment by vladimirlisovets** [comment]
Sure - here is the part I was referring to

```
  $(window).load(getFromHash);

  $(window).bind('hashchange',  getFromHash);

  function getFromHash() {

    switch(window.location.hash) {

      case '#/about/me': 
        $('.pane#aboutme').css('display','block');
      break;

      case '#/about/skills/languages':
        $('.pane#languages').css('display','block');
      break;

      default:
        $('.pane').css('display','none'); 
      break;

    }

  }
```

There are no steps like _**#/about/me**_, or _**#/about/skills/languages**_ - So when I try to initially use them with the function **load()** (**http://localhost/#/about/me**) it is redirected to the first step **by the impress.js script**, once there is no step with that anchor.

However, changing the the anchor during _runtime_ works perfectly binding the _hashchange_.

Thanks for your response and time - Vlad.

**Comment by FagnerMartinsBrack** [comment]
Sorry that I didn't made myself clear, but what I meant by "Working example" was providing some URL in which, using the code in the master branch, could show the problem using a minimum amount of code in order for someone to debug it. My suggestion would be something like http://jsfiddle.net or http://jsbin.com

If it is not possible, that's ok, your explanation should be enough. It is just that it would make it easy to get an early response if there was a live example that could be inspected later.

**Comment by vladimirlisovets** [comment]
Sadly it won't work in jsfiddle or jsbin - I can send you screenshots. It may give you the idea of what's happening.

**Comment by FagnerMartinsBrack** [comment]
Unfortunately there is not much anyone can do objectively without a small live example to debug (one or two steps). Maybe the screenshots will help, but without a reduced test case it might be much harder to find the problem, unless it is pretty obvious. We are in the process of retaking impress.js development so that might take some time for us to look into.

**Comment by vladimirlisovets** [comment]
It does not seem to be a problem - it may be a configuration to start from the first step when the anchor  does not coincide with any existing step.

I was hoping that some developer or supporter of impress.js would know the function that may be doing it.

I've a video that I'll upload and send to you - so you can see the behaviour.

It's something pretty simple. it's all about knowledge of the source code.

Thanks FagernMartinsBrack for your support till this moment - I really appreicate that.

When I finish this project I'll create a repo with the web adaptation of impress js.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again

**Comment by FagnerMartinsBrack** [comment]
By the way, maybe this is related to https://github.com/impress/impress.js/issues/408?
