### ISSUE TITLE
Remove unused branches RGSoC and dev

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#521]
@bartaz sorry to bother, but what are the branches `RGSoC` and `dev` for? They seem to be sitting there for a while so there seems to be no reason to keep them. Can we remove it or there is anything important that justifies keeping them?

**Comment by bartaz** [comment]
`RGSoC` was meant for some Rails Girls Summer of Code work, but I guess it wasn't used at all, so it's safe to remove.

`dev` was my main development branch, so all new commits were going to `dev` first, landing in `master` for releases. I guess at this point `master` is already newer than `dev` as some PRs were merged, so if we don't want to maintain separate development branch it may be free to delete too.

**Comment by FagnerMartinsBrack** [comment]
> Dev branch is 2 commits ahead, 37 commits behind master

We should remove `RGSoC` then and pull the 2 commits from `dev` to `master`.

**Comment by FagnerMartinsBrack** [comment]
Removed both branches, the only difference in `dev` was #379 that was landed there.
