### ISSUE TITLE
choiceschances.com redirecting, may be compromised

### ISSUE THREAD

**Issue by carywreams** [impress/impress.js#524]
checking the sample sites found this one re-directing to different sites.
while not your problem, you may want to remove the link here. The source file link is still good.

**Comment by Pierstoval** [comment]
If you mean in the [Demos wiki](https://github.com/impress/impress.js/wiki/Examples-and-demos) I solved this :+1:

**Comment by FagnerMartinsBrack** [comment]
I don't see a reason for keeping sites that don't work anymore with strikethrough. What if we removed them and cross referenced the change to this issue? Also, we need to cleanup that Wiki and keep only stuff that matters, I have a task to do that on #512

**Comment by Pierstoval** [comment]
I will take care of the wiki then, I saw you have plenty of work with PRs and issues :wink:

**Comment by FagnerMartinsBrack** [comment]
hehe, thx with that.

**Comment by FagnerMartinsBrack** [comment]
If possible just mark the task done once all is cleared up ;)

**Comment by FagnerMartinsBrack** [comment]
Just saw the changes in the Wiki, Amazing! :D :+1: :tada: 

What if we open a specific issue to discuss about Wiki content revamp? Such as how to prevent spam, what to put in the front-page, etc?

**Comment by carywreams** [comment]
looks good, thanks
no so skilled with the icons
"so, "two thumbs up

**Comment by Pierstoval** [comment]
@FagnerMartinsBrack Very good idea for the wiki issue!
The wiki still has to be cleaned but the basics are good now.

**Comment by FagnerMartinsBrack** [comment]
@Pierstoval Want to create that issue and link it here perhaps?

**Comment by Pierstoval** [comment]
Nope, you can do it, I'll just clean what I need to clean (the links I haven't checked yet, I'll look at this soon) and let the rest of the team manage :) As I said on Twitter I have to leave OpenSource projects for a while for personal reasons (mostly because of the time needed for these projects) :wink:

**Comment by FagnerMartinsBrack** [comment]
=(

**Comment by FagnerMartinsBrack** [comment]
@Pierstoval Are you still looking at the Wiki or have you finished the cleanup? I am checking if this issue can be closed.

**Comment by FagnerMartinsBrack** [comment]
Ping @Pierstoval :)

**Comment by FagnerMartinsBrack** [comment]
The cleanup of the Wiki seems to be ok and choiceschances.com doesn't exist anymore there. Closing then..
