### ISSUE TITLE
Create possibility to add new steps and change properties after presentation starts

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#537]
By making impress.js being able to change it's properties after it is being started we will close one of the most requested features so far.

This issue groups all the requests that will be fixed once impress.js allow changing it's properties dynamically.

**Comment by henrikingo** [comment]
I had a need for this for my impressionist project (an impress.js editor). It was surprisingly easy, almost like a single line change (plus some refactoring) to impress.js core. Committed to my fork here:
https://github.com/henrikingo/impress.js/commit/d8f21f303e604374177d9c53edb1c381a66a5d2a

I'm glad I could "accidentally" stumble into implementing this much requested feature!

**Comment by henrikingo** [comment]
Above is now merged to master. If you made changes to the DOM, calling `goto()` will now redraw the presentation.
