### ISSUE TITLE
Make it possible to finish the presentation and not loop through it

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#538]
The problem is that repeating the presentation from the beginning is too coupled to a talk presentation style. We need to decouple the behavior from talk-specific to general purpose.

**Comment by henrikingo** [comment]
FYI, in the plugins I've created, this is now possible with the [stop plugin](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/stop/README.md).

**Comment by henrikingo** [comment]
stop plugin is now merged to master.
