### ISSUE TITLE
Make the navigation optional or allow override

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#539]
The navigation is coupled for a talk presentation usage. We should allow the developer either to override the navigation completely or make the navigation optional.

**Comment by henrikingo** [comment]
Hi

I have now implemented [a pre-stepleave api](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/README.md#pre-stepleave-plugins) that includes the ability to change the next step to move to (including not to move anywhere), or to change the transitionDuration. See [goto](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/goto), [skip](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/skip) and [stop](https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/stop) plugins for examples using this api.

**Comment by henrikingo** [comment]
Above mentioned plugins are now merged to master.
