### ISSUE TITLE
Rewrite Readme

### ISSUE THREAD

**Issue by mattlockyer** [impress/impress.js#540]
Even as a developer I found your readme elitist and offensive.

There's always a nice alternative to get your point across, consider:

Impress.js was written for developers and requires some basic knowledge of HTML, CSS and JavaScript to create something amazing.

**Comment by FagnerMartinsBrack** [comment]
@mattlockyer 

Can you please elaborate why the readme was elitist and offensive? Specifically in which points?

I ask this because the readme is on for years and AFAIK this is the first time someone reports something like this, if the readme make someone feel offended, we will gladly change it.

**Comment by mattlockyer** [comment]
This paragraph:

"If you have no idea what I mean by that, or you just clicked that link above and got very confused by all these strange characters that got displayed on your screen, it's a sign, that impress.js is not for you."

Could be rephrased as I mentioned in my comment.

By referring to your repository as "may not be for you" you are discouraging use, for example a novice developer who may think you are referring to them, but may be able to use impress.

I simply don't see the point of this language as it appears to draw some special line in the sand between devs and "others".

This does not help others in an industry that already suffers from such a stigma.

**Comment by FagnerMartinsBrack** [comment]
I agree and I am pretty sure @impress/mergers will be ok with that, want to create a Pull Request?

**Comment by mattlockyer** [comment]
Done, thanks for letting me help out.

**Comment by FagnerMartinsBrack** [comment]
Just a X-ref: #542

**Comment by FagnerMartinsBrack** [comment]
I made some comments there cause it seems more stuff was changed than just the first paragraph. Let me know if you are aware of how to change the Pull Request after it is sent, if not I can change it for you when I commit it into `master`.
