### ISSUE TITLE
higher quality logo?

### ISSUE THREAD

**Issue by bkeepers** [impress/impress.js#543]
I was making a visualization of the most popular projects on GitHub, and noticed that the logo for the @impress organization is very pixilated. Do you have a higher quality version?

Also: congrats on being one of the most popular projects on GitHub!  🎉 

<img width="852" alt="localhost_4000__4" src="https://cloud.githubusercontent.com/assets/173/14111375/4b09a8ec-f57f-11e5-90f3-16ff8bbbd2c9.png">

**Comment by FagnerMartinsBrack** [comment]
Ping @bartaz

**Comment by bartaz** [comment]
Oh, sorry for not noticing it earlier. It was quite a quick icon added when I created the organisation.

@bkeepers thanks for heads up - I updated the logo to have higher res!
