### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by ax3l** [impress/impress.js#544]
A bit less general then my question [here](https://github.com/impress/impress.js/issues/197#issuecomment-203985520) but still useful:

Can one define a *global* background image *in a arbitrarily oriented plane (with width/height) in 3D* somehow?

I tried via css on `#impress` but just got a static, not co-moving background.

**Comment by ax3l** [comment]
Ok, I solved that for now by just creating a non-step `div` with absolute positioning
```html
<div id="impress" data-width="1920" data-height="1080" data-max-scale="8">
    <div id="title" class="step" data-x="0" data-y="-3000" data-z="200" data-rotate-x="-20">
        something
    </div>
    <div id="moreSteps" class="step" data-x="0" data-y="-2000" data-z="200" data-rotate-x="-20">
        something2
    </div>
    <div id="overview" class="step" data-x="0" data-y="0" data-scale="8">
        &nbsp;
    </div>

    <div id="backgroundStatic" style="width:15360px; height:8640px; transform: translateX(-50%) translateY(-50%);">
        <img alt="world map" src="img/my_large_background.svg" width="100%" />
    </div>
</div>
```

**Comment by FagnerMartinsBrack** [comment]
> Ok, I solved that for now by just creating a non-step div with absolute positioning

Glad you find the solution, closing then.
