### ISSUE TITLE
Add slide but not have it be part of the presentation?

### ISSUE THREAD

**Issue by ahainen** [impress/impress.js#552]
Hi - First time posting on github ever, I'm looking for an FAQ section or what not, sorry if this is posted in the wrong area.

I love impress.js, one question: is there any way to add a <slide> but not have it be part of the presentation? As in I want to just have elements in 3D positioned and rotated, but not actual things that the arrow keys navigate to. Just elements for background and filler that I can position in the same way I position <step slides>

Thanks!

**Comment by bartaz** [comment]
Not yet unfortunately. This has been reported couple of times and for sure is on our radar as a feature in the future, but it's not possible with current impress.js.

The workaround to achieve that (other than doing it all in CSS) is to create a steps in impress.js presentation and put those 'background' elements in the end of the presentation slides list. So when you present you just don't navigate further than the last slide. This obviously has a drawback that is anyone else will navigate the presentation (for example on-line) they could access these.

A workaround for that could be adding a custom handler for 'impress:stepleave' event on last real slide to navigate to first slide (and skip the ones that are meant for background).

**Comment by ahainen** [comment]
Awesome, thanks for the reply, much appreciated!

**Comment by FagnerMartinsBrack** [comment]
I guess we could gather the most asked questions and create a FAQ with those. Also, maybe we could suggest questions on StackOverflow under the tag `impress.js`, it has a much better SEO there than Github.

@bartaz thoughts? We don't have a specific strategy on this.

**Comment by FagnerMartinsBrack** [comment]
Closing this since it appears to be solved.
