### ISSUE TITLE
API Extension: number of slides and current slide for mousewheel implementation

### ISSUE THREAD

**Issue by mtancoigne** [impress/impress.js#554]
Hi,

The current API lacks the support for current step and current slide (number and id...), which can be a nice thing to have...

[Gist](https://gist.github.com/mtancoigne/1b84eda8459d3a92137de8b64746058d)

**Comment by FagnerMartinsBrack** [comment]
This was requested to be able to implement the mousewheel as a plugin, see https://github.com/impress/impress.js/pull/553#issuecomment-213791944 for context.

Need to revisit this in the future and see what needs to be done to fix this use case, either by implementing mousewheel in the core, or exposing those attributes for a per use case implementation.

**Comment by henrikingo** [comment]
A few comments.

I would argue getting the current step element is well supported in the current API. If you need to know the current element, you can do one of two things:
- `getElementById(location.hash)` (where, location.hash is the id)
- listen to the `impress:stepenter` event, which has the new step element in `event.target`. (Then save it in your own variable for later reference.)

**Comment by henrikingo** [comment]
As I'm maintainer now, I'm closing with reference to my previous comment on how to get the current slide nr. Also see `progress` plugin that does show current slide and total nr of slides in a progress bar.
