### ISSUE TITLE
kab'

### ISSUE THREAD

**Issue by tinortiz** [impress/impress.js#561]
**Make sure these boxes are checked before submitting your issue, thank you!**

- [ ] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/CONTRIBUTING.md#issues).
- [ ] If am reporting a bug, I have a [simplified example](https://sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [ ] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by FagnerMartinsBrack** [comment]
I will assume this issue was created by mistake. Closing then...
