### ISSUE TITLE
Test improvement plan for 0.6.1

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#575]
We need to increase test coverage. Right now it only runs in Chrome and has basic integration tests.
- [x] Improve the number of browsers where the tests are run. Add Firefox, Edge, IE and other desktop browsers that fully support the required features (investigate which browsers do fully support the required features) (https://github.com/impress/impress.js/pull/579).
- [ ] Improve the handling of fixtures. Create a way to prepare fixtures to create many tests with different fixtures without using only one fixture for all of them. This reduces the chances of side effects inside the tests.
- [ ] Improve the handling of instance testing. Find a way to run several instances of impress.js in a single test execution. Right now we are using a single page to run everything (only one instance of impress.js).
- [ ] Add coverage for the keyboard navigation, so that we can ensure that complex features like https://github.com/impress/impress.js/pull/550 do not break other things.

@impress/mergers thoughts? Any non-functional thing, documentation fix or small bug fix you believe is worth tackling in the [next patch 0.6.1](https://github.com/impress/impress.js/milestone/3)?

**Comment by henrikingo** [comment]
Points 2 and 4 should be taken care of in master now (one way or another). Not quite sure what you meant with point 3.

I'll close this, I'm about to open a series of new testing related tickets anyway, based on the new state of the codebase.
