### ISSUE TITLE
Resolved: Pause, Resume, and Navigation Manipulation

### ISSUE THREAD

**Issue by RyanG26** [impress/impress.js#578]
**Make sure these boxes are checked before submitting your issue, thank you!**
- [x] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/CONTRIBUTING.md#issues).
- [x] If am reporting a bug, I have a [simplified example](https://sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

I had a few use cases for hijacking the navigation controls during certain steps for sub interactions and duration changes that needed more than the .impress-on, .active, and .present classes, so I created [impause.js](https://github.com/RyanG26/impause.js).

Should be able to help with a lot of the questions I I saw while googling for my own answers.

**Comment by FagnerMartinsBrack** [comment]
It seems that the functionality is too restricted to a single use case, so we encourage building extensions to impress.js. Thanks for sharing it!

**Comment by henrikingo** [comment]
If I follow correctly, similar feature is now implemented by the autoplay plugin.
