### ISSUE TITLE
Demo with presentation mode

### ISSUE THREAD

**Issue by yarnball** [impress/impress.js#581]
Hi,

Your examples look great (such as http://henrikingo.github.io/presentations/MongoDB%20and%20GIS%20-%20Helsinki%20AGILE%202016)

However, download the source files (html/css/js) and trying to manipulate the presentation does not work. It causes several ugly css conflicts and issues.

Could you please upload the source files of this in a git repo? Alternatively- just the parts that enable the presenter mode would be great.

Thanks

**Comment by FagnerMartinsBrack** [comment]
You can probably check @henrikingo's main page at http://henrikingo.github.io/, there's a lot of information there.

Closing as there isn't anything actionable here.

**Comment by yarnball** [comment]
I have checked  @henrikingo 's main page- but there is no information on how to get the presenter mode or how to just download one of his already made products.

**Comment by henrikingo** [comment]
Hi @yarnball!

All of those *are* in a github repo, here: https://github.com/henrikingo/presentations

(If you have further questions or comments, feel free to use the issue tracker for that repo.)

**Comment by yarnball** [comment]
@henrikingo Thank you ! Very nice work
