### ISSUE TITLE
qunitjs@2.0.0-rc1 does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by elopio** [impress/impress.js#585]
I'm trying to do npm install in an ubuntu xenial lxc machine with node 4.4.4, but it fails because there is a conflict with the depedencies:

npm --cache-min=Infinity install
npm WARN peerDependencies The peer dependency qunitjs@^1.14.0 included from karma-qunit will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/
> sauce-connect-launcher@0.13.0 postinstall /root/parts/impressjs/build/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher
> node scripts/install.js

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/root/parts/impressjs/install/bin/node" "/root/parts/impressjs/install/bin/npm" "--cache-min=Infinity" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package qunitjs@2.0.0-rc1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-qunit@1.0.0 wants qunitjs@^1.14.0

npm ERR! Please include the following file with any support request:
npm ERR!     /root/parts/impressjs/build/npm-debug.log

**Comment by FagnerMartinsBrack** [comment]
Have you tried running on node 6? Our dev environment doesn't have big node support, maybe it's worth documenting it.

**Comment by elopio** [comment]
Do you mean node 4.6? That failed with the same error.

**Comment by FagnerMartinsBrack** [comment]
> Do you mean node 4.6? That failed with the same error.

No, [node 6](https://nodejs.org/en/blog/release/v6.0.0/).

**Comment by elopio** [comment]
ah, right, sorry for being dense :)
That works indeed. Thank you!

**Comment by FagnerMartinsBrack** [comment]
I have created an issue to document the node version, so that this kind of issue doesn't happen anymore, see https://github.com/impress/impress.js/issues/589.

Thanks!
