### ISSUE TITLE
The check items when reporting a bug have wrong URLs

### ISSUE THREAD

**Issue by elopio** [impress/impress.js#586]
When I am going to report a new bug, a checklist is prefilled in this text box. It has two errors:

Instead of 
https://github.com/impress/impress.js/blob/master/CONTRIBUTING.md#issues 
it should be
https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues

Instead of 
https://sscce.org/
it should be:
http://www.sscce.org/

**Comment by FagnerMartinsBrack** [comment]
Fell free to open a PR with the suggested improvements. See https://github.com/impress/impress.js/tree/da4c08aa2311f8d2e057d98d7f8fd515e48218c4/.github.

**Comment by jdalton** [comment]
Moved to #587.
