### ISSUE TITLE
Create a maintainers guidelines

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#588]
@bartaz @jdalton I have a few suggestions on how to approach merging PRs, opening as an experiment for discussion:
1. Require one Github review approval, otherwise, block merging (including admins).
2. Always use Github "squash and merge" instead of the other options, leveraging the idea of [one concern per PR](https://medium.com/@fagnerbrack/one-pull-request-one-concern-e84a27dfe9f1).
3. Any additional things we should make the standard?

Note: Maybe `1` doesn't matter much since we don't have a lot of active maintainers?

**Comment by FagnerMartinsBrack** [comment]
Bump.

**Comment by jdalton** [comment]
I'm laid back, whatever process you all dig is fine by me.

**Comment by bartaz** [comment]
I'm fine with that. As you said, 1) doesn't matter that much at this point.

**Comment by FagnerMartinsBrack** [comment]
I agree with @bartaz, at this point makes no sense requiring strong review, although it's always desirable :D.

See https://github.com/impress/impress.js/pull/592.

**Comment by and3rson** [comment]
Nice to see the project is still alive and doing well :)

**Comment by FagnerMartinsBrack** [comment]
@and3rson It's slowly going, we are [focusing on the tests now](https://github.com/impress/impress.js/issues/575). Any help is appreciated.

**Comment by henrikingo** [comment]
I guess situation is much simpler now compared to when this ticket was opened, so I will just state the guideline here and close this ticket: Going forward, I will review all PRs. 

I will use both rebase-and-ff and squashing when convenient, time will tell if it's always meaningful and practical.

Project will follow meritocracy, so when we hopefully get more contributors now, those that show a sustained interest in contributing, can then get responsibility to be reviewers in the areas they have contributed to and are intimately familiar with. (If we get that far, writing down some common guidelines, including about coding style / structure and so on, may be needed.)
