### ISSUE TITLE
Multiple presentation roots on a single page?

### ISSUE THREAD

**Issue by henrikingo** [impress/impress.js#599]
**Make sure these boxes are checked before submitting your issue, thank you!**

- [ ] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [ ] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [ ] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by henrikingo** [comment]
Hi @bartaz / anyone

I've recently been thinking more about the fact that impress.js actually supports multiple presentations on a single HTML page. While this isn't really covered in any documentation, the code clearly supports calling `impress("other-root-div").init()`.

I was just wondering if you have ever used, or are aware of anyone ever actually using this capability, and if yes, what would it look like? Is there a link to such a presentation?

It seems to me a presentation with multiple root divs would cause each of the presentations to show the active step towards the viewport? The Navigation Events plugin at the end of impress.js would register event listeners once for each root element, so that when I press space, each of the initialized root elements will move a step forward "together"?

**Comment by FagnerMartinsBrack** [comment]
@henrikingo There was some discussion [when I was building the API docs](https://github.com/impress/impress.js/pull/563#r66050207). We didn't document it, but if somebody finds evidence that there's usage in the wild for multiple roots then we probably need to add it somewhere if we want to support it.

**Comment by henrikingo** [comment]
Thanks Fagner!

That roughly what I was asking for. (I'll leave this issue open for a while just in case someone has something to add, which would be interesting to know.)

**Comment by FagnerMartinsBrack** [comment]
@henrikingo Do we consider this really important for now? It seems that once we resolve https://github.com/impress/impress.js/issues/81 this requirement is also going to be fixed as a bonus. When that happens, we can choose to document properly how to add impress in multiple roots.

Make sense?

**Comment by henrikingo** [comment]
I don't think this is the same as #81. After all, that just adds granularity to navigate a single presentation.

Whether this is important, I don't know. That's what I was trying to understand and get input.

I don't see that there's a specific action for now, this is just a request for comment type of issue. If it's ok with you, I'd like to keep it open for a couple more weeks, but you could ignore it from a backlog point of view. I'd close it eventually.

**Comment by FagnerMartinsBrack** [comment]
That's reasonable. I would also be interested to know how it's being used in the wild, it's just that I find very hard to get efficient feedback just from the Github issues. My impression is that most developers that use impress.js are not very active in the development, except for a few of them who create issues or PRs and care to follow through, we can see them in the open issues/PRs after the [triage of a few months back](https://github.com/impress/impress.js/issues/512).

I guess the best way to get a good information  about this would be from @bartaz, and even he cannot predict how it's being used in the wild. My best guess would be to look at the forks or the sites in the Wiki using impress, then we can have an idea of how that feature is being used and document it for posterity. Although, it will be a pretty big work to do that 😆
