### ISSUE TITLE
Typings support on Ionic2

### ISSUE THREAD

**Issue by CarlosAyala** [impress/impress.js#601]
Hi!.

When I load "typings" for impress.js,  The file index.d.ts was created with the content.

`interface Impress {
    init(): void;
    getStep(step: any): any;
    goto(element: any, duration?: number): any;
    prev(): any;
    next(): any;
}

declare function impress(): Impress;`

How I can import this to my project?

This code don't work

`import` impress from 'impress.js';

**Comment by henrikingo** [comment]
Hi @CarlosAyala 

I'm afraid nobody here is familiar with Ionic2, so we won't be able to help you.

Did you see [the documentation file](https://github.com/impress/impress.js/blob/master/DOCUMENTATION.md)? I hope it's of some help.
