### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by ArtNous** [impress/impress.js#605]
I would like impress.js in Spanish. I can contribute with the traduction for the Spanish community. It can have a documentation in that language.

- [x] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [x] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by henrikingo** [comment]
Hi @ArtNous 

Currently there is no framework for translation support. I don't know if we want to introduce one either, but if we did, for sure it would be something very minimalistic. There's a design goal that impress.js remains self contained, so we don't use any external libraries like jquery, underscore... anything.

That said, impress.js itself doesn't really show that much text anyway. (There are a few UI buttons now, but that's about it.) Perhaps more interesting would be to translate DOCUMENTATION.md, README.md and so on. And of course the content - and maybe even code comments - of the demo presentations too.

If that's what you wanted to do, I recommend you simply fork the impress.js, and translate those texts in your own repo. We could then link to this Spanish translation from [the wiki](https://github.com/impress/impress.js/wiki).

**Comment by henrikingo** [comment]
Closing for lack of response. If you have further questions, please reopen this issue.
