### ISSUE TITLE
No transition from Powerpoint

### ISSUE THREAD

**Issue by iamvidge** [impress/impress.js#606]
Hello, could you please add transition support from Powerpoint? Would really help me get started..

**Comment by vorpalvorpal** [comment]
[Hovercraft](https://github.com/regebro/hovercraft) provides a (fairly) user-friendly way to use impress.js. It uses [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) files which are a human-readable format. You might be able to save your powerpoint presentation as a docx and then use [pandoc](https://pandoc.org/) to convert it to reStructuredText, but I think you would need to do so much manual cleaning up at the end of that process it might not be worth it.

**Comment by henrikingo** [comment]
Hi iamvidge

To be clear, if you have existing PowerPoint slides, and would like to somehow convert them into impress.js, that will never work.

If you want to easily create some simple rectangular slides, maybe you want to look at this demo presentation in my impress.js fork:
http://henrikingo.github.io/impress.js/examples/classic-slides/
https://github.com/henrikingo/impress.js/tree/myfork/examples/classic-slides

In particular, it includes things like Markdown support. And yes, that was inspired by Hovercraft, which I liked, but now you don't need an external tool, rather it is supported in impress.js itself.

I'm now actively working on merging the above into the official impress.js.
