### ISSUE TITLE
CSS transform (rotate) inside step

### ISSUE THREAD

**Issue by CountZukula** [impress/impress.js#607]
Hi all,

I am currently finishing up a presentation and i'm encountering a specific problem (maybe due to my misuse of impress.js). Inside a step I am putting several images, which I transform so that they appear to be in a stack (on on top of the other, rotateY(-20deg)). This works well within the step itself, and I'm adding some animation so they appear to be flipping from one to the other. 

However, the rotation (and translation) I'm applying manually through css is only visible when the step is active. Seen from the previous step, the rotation is not applied yet. As far as my current knowledge goes, I see only one possible solution, but I'm not sure how I would implement this:

Put the flipping images in a separate step, which is rotated by impress.js. Then add a step on top, not rotated, with some text in it, so the images appear to be rotated from the perspective of the text step. However, then I would have to be able to auto-skip the image-step, which I don't know how to do. I hope this made some kind of sense to anyone reading this, if not, let me know :).

Best regards

![screenshot from 2017-03-01 22-37-03](https://cloud.githubusercontent.com/assets/11455912/23482587/eb0dd1ce-fecf-11e6-97b0-5f6d98e5dc06.png)
![screenshot from 2017-03-01 22-37-18](https://cloud.githubusercontent.com/assets/11455912/23482590/eccb7e3a-fecf-11e6-80a1-67c587b1c013.png)

**Comment by FagnerMartinsBrack** [comment]
> I am currently finishing up a presentation and i'm encountering a specific problem (maybe due to my misuse of impress.js). Inside a step I am putting several images, which I transform so that they appear to be in a stack (on on top of the other, rotateY(-20deg)). This works well within the step itself, and I'm adding some animation so they appear to be flipping from one to the other.

impress.js was not created for flipping or stacking images, so its core adjusts the step (camera) to position itself in front of a slide.

> However, the rotation (and translation) I'm applying manually through css is only visible when the step is active. Seen from the previous step, the rotation is not applied yet. As far as my current knowledge goes, I see only one possible solution, but I'm not sure how I would implement this:

Probably you want to create a step that shows the flipping and implement the flipping using CSS inside the step, not using impress.js steps to achieve that.

The problem is not very easy to understand.

> Put the flipping images in a separate step, which is rotated by impress.js. Then add a step on top, not rotated, with some text in it, so the images appear to be rotated from the perspective of the text step. However, then I would have to be able to auto-skip the image-step, which I don't know how to do. I hope this made some kind of sense to anyone reading this, if not, let me know :).

I didn't get it :D

**Comment by CountZukula** [comment]
I will try to clarify :) - first of all, i _am_ putting everything inside a step, then applying CSS, to be sure -

In the first screenshot, you see three images, superimposed. They are the content of 1 slide, together with the text "if we get a list of ...". I rotate those images using css (transform: rotateY(-20deg), for example), and animate them using -webkit-keyframes. This looks good when the slide is .active. But when you look at the content from the _previous_ slide (see screenshot 2), then the images are not rotated (they're facing the camera straight, you see them at the bottom). The -webkit-keyframes are still working though: their animation is continuing.

When you then go to the next slide again, containing the images, there's a moment of hesitation, then the rotation is applied and everything looks like it supposed to.

**Comment by CountZukula** [comment]
Okay, i'll add this as an additional comment. The described behaviour goes away when I apply opacity:1 to the afflicted slide. Then all rotations are seen, from within the slide and from outside the slide. Weird?

**Comment by FagnerMartinsBrack** [comment]
@CountZukula A runnable example showing the problem would be better than a detailed explanation, I guess.

**Comment by CountZukula** [comment]
Indeed, the attachment should be included now. The attached file contains all my dirty work in progress, the file to open is pres.html. pres2.css contains the main body of css, including the _fix_ where I set opacity 1:
```
#problem3intro4 {
    /*opacity:1;*/
}
``` 

Uncomment that line, and the problem seems to be alleviated.

[pres.tar.gz](https://github.com/impress/impress.js/files/812249/pres.tar.gz)

**Comment by FagnerMartinsBrack** [comment]
I see, it looks like something is influencing on the position of the step. Can you provide a [SSCCE](http://sscce.org) pointing out exactly which circumstances the problem occur?

It's actually [one of the requirements](https://github.com/impress/impress.js/blob/82bc45e6b002a6bb02b032f6bf2405b6e4769ff1/.github/ISSUE_TEMPLATE.md) to post an issue because that can clarify where the problem lies (impress.js or the browser).

**Comment by henrikingo** [comment]
Hi @CountZukula 

You seem to be fully capable of doing your own css, but regarding the alternative of putting (background) graphics in a separate step, which has to be skipped during navigation, this is in fact an existing feature request, and I have implemented it in a fork:
https://github.com/henrikingo/impress.js/tree/myfork/src/plugins/skip

As you say, the benefit here is that the impress.js framework will do the positioning for free. Otoh, I don't see that it would necessarily rotate (flip) the images as you're now doing.

**Comment by CountZukula** [comment]
Sorry, should have given a MWE straight away... I guess it's a conflict with the pres.css, if I disable that the problem goes away. But then it seems I lose a lot of the functionality that the impress.js demo offers.

[SSCE.zip](https://github.com/impress/impress.js/files/813631/SSCE.zip)

**Comment by FagnerMartinsBrack** [comment]
> I guess it's a conflict with the pres.css, if I disable that the problem goes away.

That file is just an example file, none of the styles are mandatory for impress.js to work (it will just have no style if you don't use it :D).

Have you tried to SSCCE `pres.css` to identify the source of the problem there?

**Comment by CountZukula** [comment]
Well, I'm in the process of finishing that presentation, and I'm on a deadline :). I'll try to give it a shot when I get some spare time...

**Comment by henrikingo** [comment]
Hi @CountZukula 

Is this issue still relevant, or did you solve your problems?

**Comment by CountZukula** [comment]
Hi Henrikingo, I'll consider it closed. I don't remember actually solving the problem but I circumvented it by disabling the .css file. Maybe I'll revisit the project in the future for archiving purposes, but that's not something for the nearby future in any case.
