### ISSUE TITLE
impress.js of ReactJS

### ISSUE THREAD

**Issue by GeorgioWan** [impress/impress.js#608]
Hi,
I'm a big fan of impress.js 😋 

Few days ago, I built a project - [**React-impressJS**](https://github.com/GeorgioWan/react-impressjs) that was used **ReactJS** to implement **impress.js**.
The usage is just like impress.js, but in react way, means that is operating **Steps** with Virtual DOM but not DOM.

I hope this project can be more attention with impress.js, make impress.js provide the better way for app of react! so, could you put this project in **official way for ReactJS of impress.js** ?

Thanks for all.

**Comment by FagnerMartinsBrack** [comment]
Hi, we don't officially support plugins that we don't work on. However, feel free to add it to the Wiki page: https://github.com/impress/impress.js/wiki/impress.js-tutorials-and-other-learning-resources

**Comment by GeorgioWan** [comment]
Hi,
Thanks for reply, I'll add it to the Wiki page of impress.js.
