### ISSUE TITLE
Alternative next slide

### ISSUE THREAD

**Issue by naraesk** [impress/impress.js#611]
Use case: I have a big presentation I'll use regularly. Sometimes I want to go into the details of a topic, sometimes not. Editing the presentation constantly or skipping all slides by hand is possible, but not really convenient. If you press Alt + arrow key, the presentation will jump to the referenced slide instead of the next slide. 

As far as I have understood impress.js something like this doesn't exist, does it?

**Comment by henrikingo** [comment]
Hi @naraesk 

Something like this is now supported in master branch. Thanks for a great suggestion!

Demo presentation: http://impress.github.io/impress.js/examples/2D-navigation/
