### ISSUE TITLE
AFrame Integration

### ISSUE THREAD

**Issue by morandd** [impress/impress.js#612]
Any plans to allow publishing Impress presentations to AFrame?

One way to do it: the script would iterate over every slide, render the contents to a canvas (not sure how to handle canvases with dimension larger than webgl's MAX_TEXTURE_SIZE) , then create an  AFrame plane object with that canvas as the texture, and using the rotation/scaling as specified in the impress. The slides would be anchored such that the main slide is always position at the AFrame component position, and the non-active slides are positioned&scaled relative to the active slide. Hopefully the animation engine should be easy to wire in. 

**Make sure these boxes are checked before submitting your issue, thank you!**

- [x ] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [ ] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [ x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by bartaz** [comment]
It's an interesting idea, bit kind of out of scope for impress.js.

AFrame uses totally different rendering than impress.js. Impress.js is based on CSS animations and transitions, AFrame internally uses Three.js and renders in WebGL. Trying to support AFrame would mean complete rewrite of impress.js to support different renderers.

While it may be interesting from technical point of view, probably it wouldn't be very practical.
