### ISSUE TITLE
Clicking on an element outside the impress canvas causes impress to go navigate

### ISSUE THREAD

**Issue by mvanroon** [impress/impress.js#613]
Impress canvas will go to next/prev slide, even though the element that was clicking might not be inside the impress root

**Make sure these boxes are checked before submitting your issue, thank you!**

- [x] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [x] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by henrikingo** [comment]
Hi @mvanroon 

Does your bug spefically happen on a touch screen? As of 1.0.0-beta1 we now use swiping instead of tapping on touch screens, so this issue should be resolved. Can you please confirm, and close this issue if yes.

**Comment by henrikingo** [comment]
Closing for lack of response and based on hoping my guess above is correct. If this still happens, please reopen.

**Comment by mvanroon** [comment]
Sorry. I opened the issue 8 months ago. I don’t have the project on my machine anymore. Cheers
