### ISSUE TITLE
How to mute sound of iframe when blur

### ISSUE THREAD

**Issue by gabriellluz** [impress/impress.js#617]
**Make sure these boxes are checked before submitting your issue, thank you!**

- [X ] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [X] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [X ] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

Hi, I'm using Impress to load iframes with videos but when I load a page, it load all videos at the same time. I'd like to know how to mute an iframe when not focused or maybe how to pause an iframe or video when not focused.

**Comment by henrikingo** [comment]
Hi @gabriellluz 

When impress moves to a step, it will trigger an "impress:stepenter" event. Correspondingly, for the step that was just finished a "impress:stepleave" event is triggered. You can catch these events in JavaScript and use them to play and stop media in your presentation.

impress.js also sets CSS classes to the div elements that are steps. The active element gets two classes: "active" and "present". I don't know if you can use CSS to manage video playback though.
