### ISSUE TITLE
Exposing defaults as global variable.

### ISSUE THREAD

**Issue by vorpalvorpal** [impress/impress.js#624]
**Make sure these boxes are checked before submitting your issue, thank you!**

- [x] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [x] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

I'm working on extending hovercraft and would like to be able to read the data in impress.js's defaults (height, width, max-scale, min-scale, perspective, transitionDuration). Could defaults be exposed as a global variable so that other js files could read/edit them?

I'm happy to submit a patch for this if others think it is a reasonable thing to be do.

**Comment by henrikingo** [comment]
I think a design goal is not to pollute the global variable space with anything else than impress() function itself. So from that point of view, the answer would be no.

But why do you need to read them? I don't think the defaults have ever changed? Also, impress.js is versioned, so if you know which version you're working with, you know what the defaults are.

You probably know this, but for completeness I'll point out that those values of course can be set in `<div id="impress" data-height="" data-width="" ...` where you obviously can read them via normal DOM methods.

**Comment by FagnerMartinsBrack** [comment]
I don't encourage people to read generated attributes from the DOM unless they are [documented](https://github.com/impress/impress.js/blob/525e4fc5f2c2da28323672ea7a41ac574475819f/DOCUMENTATION.md). If consumers start inferring things from the markup, the markup becomes rigid and we wouldn't be able to make changes if we want to because there will be no way to find out who's relying on them.

**Comment by bartaz** [comment]
I guess in theory we could expose them inside the impress global namespace, something like `impress.defaultConfig = { height, width, ... }`.
On the other hand if we do it it may feel tempting to change them from outside of impress.js which may have some unexpected consequences.

**Comment by FagnerMartinsBrack** [comment]
> [...] it may feel tempting to change them from outside of impress.js which may have some unexpected consequences.

We might be able to [freeze them](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) or document as read-only properties (or both).

**Comment by henrikingo** [comment]
> I wouldn't encourage people to read generated attributes from the DOM unless they are documented.

I didn't realize you had not documented the attributes to the root element. I'll make a note to do that in the future (unless of course you beat me to it). Note that some of these have been, for example, documented in the index.html demo presentation.

(To clarify: These aren't generated DOM attributes, rather data-* attributes used for input.)

**Comment by FagnerMartinsBrack** [comment]
> These aren't generated DOM attributes, rather data-* attributes used for input.

[The OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) is requesting access for height, width, max-scale, min-scale, perspective, and transitionDuration, not the root or step element attributes. AFAIK those are internals and therefore they haven't been documented [here](https://github.com/impress/impress.js/blob/525e4fc5f2c2da28323672ea7a41ac574475819f/DOCUMENTATION.md#2d-coordinates-positioning-data-x-data-y) yet.

We probably need to understand how @vorpalvorpal need to integrate with hovercraft, perhaps a PR with an example would make things clearer?

At this point, we have no context so it's hard to know what's necessary.

**Comment by henrikingo** [comment]
> The OP is requesting

Ah, sorry. I read the thread as if you were responding to my comment.

**Comment by FagnerMartinsBrack** [comment]
I was, just realized the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) intent now 😅

**Comment by vorpalvorpal** [comment]
Wow, the last time I checked on impress.js the project seemed dead. It's fantastic to see so much activity! So, I wrote [an extension to hovercraft](https://github.com/vorpalvorpal/hovercraft/blob/master/local_directives/media/media.js) to allow elements to take up the entire screen (part of a larger extension allowing videos and audio). To do this I work out an appropriate scaling factor based on the size of the the slide.

I didn't take the time to read impress.js closely, however, and thought that users were expected to edit the defaults to change the slide size (hence why I wanted access to whatever the user had chosen). However, now I see I was mistaken. It might still be nice to have the defaults exposed so that if they do change some time in the future, extensions such as mine don't break, however I entirely understand why you would be cautious to do so.

Thanks for all the replies and sorry for not taking the time to read the source properly. Egg on my face. Lesson learned.

**Comment by FagnerMartinsBrack** [comment]
@vorpalvorpal So this issue is not an issue anymore?

**Comment by vorpalvorpal** [comment]
Well I was going to say, yes, this should probably be closed, but actually, maybe not. If as @bartaz suggested, they were exposed as impress.defaultConfig (or similar) they wouldn't pollute the global namespace and if, rather than being defined in impress.defaultConfig, they were merely copied there after being defined internally, there would be no problems with people trying to change them from outside impress (since they don't actually do anything other than report the internal values). It would, however, allow you guys and gals to change the defaults at some stage without breaking any third-party applications that relied on those defaults.

**Comment by FagnerMartinsBrack** [comment]
@vorpalvorpal The point is that we don't want to add more APIs without having a strong reason for doing so. New APIs incur a maintainability cost we try to avoid as much as possible. Besides a "nice to have", do we still have a strong case for this request?

**Comment by henrikingo** [comment]
To second @FagnerMartinsBrack here: did those defaults ever change in the history of impress.js? Do we have any reason to think they would do so in the future? Since they're just constants, you know their values already.

**Comment by vorpalvorpal** [comment]
Fair enough. Well I'll close this request.
