### ISSUE TITLE
Where is documentation for the overview?

### ISSUE THREAD

**Issue by steveknoblock** [impress/impress.js#629]
The overview feature does not seem to be mentioned in the documents. Unless someone can point to where it is. There's no explanation of how this works or how to control or design it.

**Make sure these boxes are checked before submitting your issue, thank you!**

- [x ] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [x ] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x ] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

**Comment by bartaz** [comment]
@steveknoblock Not sure what you mean exactly by 'overview feature', as there are no such 'feature' in impress.js.

If you are referring to an overview step in demo presentation it's just a manually added empty step of presentation positioned in a way to show all the other slides. Nothing more. No magic there, just tweaking `data-*` attributes until it looks good.

**Comment by FagnerMartinsBrack** [comment]
@steveknoblock Does @bartaz comment answers your question?
