### ISSUE TITLE
next slide number

### ISSUE THREAD

**Issue by vorpalvorpal** [impress/impress.js#634]
**Make sure these boxes are checked before submitting your issue, thank you!**

- [x] I have read and complied with the [Issues Contributing Guidelines](https://github.com/impress/impress.js/blob/master/.github/CONTRIBUTING.md#issues).
- [x] If am reporting a bug, I have a [simplified example](http://www.sscce.org/) on [Pastebin](https://pastebin.com/) or [JsFiddle](https://jsfiddle.net/) that reproduces the issue.
- [x] I have used the [Search Tool](https://github.com/impress/impress.js/search) to make sure someone haven't already reported my issue or feature request.

Would the api be able to be extended so that the number of the slide we are about to go to is available on impress:stepleave? Using "parseInt(event.target.getAttribute('step')) + 1" gets us the number of the next slide if we are going forwards, but what if we are going backwards (in which case it should be current step -1) or we are going directly to a slide?

**Comment by henrikingo** [comment]
Hi @vorpalvorpal 

In my fork, which is in the process of getting merged, I've added exactly that: https://github.com/henrikingo/impress.js/blob/myfork/src/impress.js#L272

The next step (the actual div element) is available in event.detail.next.

There is also a new api for "prestepleave" events, where a plugin gets executed before the stepleave happens. Such plugins can also set the event.detail.next to another value, in which case the transition will happen to that step instead.

**Comment by vorpalvorpal** [comment]
Thanks @henrikingo. I'll put a little comment in my code to update it once all your great work is merged over.
