### ISSUE TITLE
Link "overview" position fixed

### ISSUE THREAD

**Issue by mpiron** [impress/impress.js#635]
Hello, 

I use impress.js for test and an would like to let all the time of the presentation a link to go to the overview. Unfortunately, the text is visible but non clikable. 
Hier is [the example!](http://cndbs-binche.be/a_effacer/impress_2017/warhammer-leo.html)
The code is: 
After the div id=impress closure 
>     <div style="position: absolute;  top:10px; left: 10px;">
>    <a href="#/overview">Vue d'ensemble</a>
>    </div>

Somebody know how to make this link usefull? 
Thank's for help

Murielle

**Comment by henrikingo** [comment]
Hi Murielle

Elements outside of steps are not clickable, because you have probably copied the CSS from the impress.js demo: https://github.com/impress/impress.js/blob/525e4fc5f2c2da28323672ea7a41ac574475819f/css/impress-demo.css#L685

You can remove that line, or add a new one for the element you want to click on and set `pointer-events:auto`.

**Comment by mpiron** [comment]
Hi Henri, 
I'll look at this tomorrow. Thank's a lot for your so quick response. 
I'm discovering gitup and impress.js. I have effectively  use _impress.js demo_ because I don't know where I have to search to found other exemples.

I hope my english is understandable... :-D

Murielle

**Comment by henrikingo** [comment]
For now, using the impress-demo.css is the most common starting point. I'm in the process of adding a few more examples in the next few weeks.

Beyond what you find in the github repository, there's also a wiki page: https://github.com/impress/impress.js/wiki/Examples-and-demos

> I hope my english is understandable... :-D

I think none of us are native English speakers (?), so you're fine!
