### ISSUE TITLE
API Documentation example for impress:stepenter callback doesn't work

### ISSUE THREAD

**Issue by amdrewnguyen** [impress/impress.js#641]
```JavaScript
var rootElement = document.getElementById( "impress" );
rootElement.addEventListener( "impress:stepenter", function() {
  var currentStep = document.querySelector( ".present" );
  console.log( "Entered the Step Element '" + currentStep.id + "'" );
});
```

If I'm understanding the source correctly, the step element only receives the `present` class as a result of `impress:stepenter` being triggered. If that's the case, using a query selector for class `present` in an `impress:stepenter` event will not reliably return the correct element. Is there a better way to get the current step on this even firing?

**Comment by henrikingo** [comment]
You're correct. Also, in general you wouldn't want to use any DOM operation to find the current step, as it is available in event.target!

Thanks for pointing this out, I will post a fix shortly.

**Comment by henrikingo** [comment]
Hi @amdrewnguyen 

I now pushed a commit to dev branch that fixes the DOCUMENTATION.md. (Will be merged to master shortly...)

Hopefully this helps you do what you're doing the way that actually works: https://github.com/impress/impress.js/blob/dev/DOCUMENTATION.md#impressapi
