### ISSUE TITLE
How do you use the presentation mode?

### ISSUE THREAD

**Issue by najamelan** [impress/impress.js#651]
I don't know if it's just me, but I can't get the presentation mode to work on both demo's linked from the readme.

This is what I would expect:
- I get a view of the currently showing slide (as in the one that's showing in the other tab on a big screen for the audience to see), the next slide and the notes for the current slide.
- When I push the arrow-right button, all three views and the notes advance to the next slide.

What actually happens:
1. When I push P, firefox aks me if I want allow popups from this site, so I click yes and the presentation opens in a new tab. The presentation tab has 2 views which automatically start playing. So I have to pause them both and put them manually on the first and second slide. When looking what's in the first tab, I get a gray overlay saying click here to open presentation. Clicking on it has no effect and there's no way to get rid of it. Ok, this is a one time problem, since now I have told ff to accept popups, so lets start over.

2. Try 2. I pause all views again, put them on the first slide and the next view on second slide. Ok, now I push arrow-right in presentation tab. Only the main view and the notes in that tab go to the next slide. The next view doesn't move, neither does the main tab with the presentation that I would like to show on a big screen.

3. What's described so far is something that works sometimes. Other times, the presentation tab doesn't load with a javascript error in the console: `window.impress is not a function`

Conclusion, to use this I would have to try loading the presentation until 1 and 3 don't happen. Pause all view. Put all views back on the first slide. For every slide advance each of the views manually. With that kind of distraction, I don't think I'll use impress, even though the demo at https://impress.github.io/impress.js has amazing transitions.

Is this functionality as intended or is it just buggy?

**Comment by henrikingo** [comment]
Hi  @najamelan 

Thanks for reporting this.

As for 1), this is a limitation or security feature of the browser. As you have noticed, after you allow popups and reload, it works fine. I don't know that there is much that impressConsole can do about this.

2) This is indeed a bug. impressConsole should turn off autoplay, as the point is for those preview windows to follow the main window. The other [example presentations](http://impress.github.io/impress.js/examples/) do not use autoplay and you should be able to verify from them that impressConsole works fine.

3) This seems odd and shouldn't happen. Is there any other error message printed together with this?

**Comment by najamelan** [comment]
I have looked at the 2d example and it does indeed work as intended here. That's cool, thanks. 
One thing that I hadn't noticed before was the next and previous buttons at the bottom of the presentation screen, which indeed correctly synchronize all views. I understand the usefulness of being able to have a quick peek at upcoming slides without changing the main screen by using the controls within the views, but I suppose with all the other stuff going wrong I was to confused to see the buttons on the bottom.

The javascript error appears just alone, but it is a sometimes bug, so I haven't yet figured out what triggers it. I suppose I had some bad luck when I just tried it out. 

About the allow popup, I know that is normal behaviour of the browser, what was just problematic is when that happens, on the main view there is the gray box that says "Click here to open the presentation view" which is impossible to remove, needing to reload the browser window. Since the presentation view should change the main view I just assumed it was better to start over, thinking that reloading the main view might break the connection between the two tabs, but I haven't even tested if that is actually the case.

I will have a look at the other example's code in order to make my own presentation so that it works, thanks for responding.

**Comment by henrikingo** [comment]
As far as I can tell, the message "Click here to open the presentation view" does not come from impressConsole.js or impress.js. (Which is actually a bit confusing, as I can't explain how the browser would know you're looking at a presentation view.)

**Comment by najamelan** [comment]
Have you seen this message or would you like me to take a screenshot to show it? I could surely also have a quick look to the code to see where it's coming from.

**Comment by henrikingo** [comment]
I have seen it myself too, every time I need to allow popups. I just can't find the text anywhere in the code.

**Comment by najamelan** [comment]
The string I see exactly is: "Click to open speaker console". It comes from [here](https://github.com/impress/impress.js/blob/cd499ed8cf1014d7151d21c94771a7495b379106/js/impress.js#L1976) but is also in the file impressConsole.js. It is being used in [this place](https://github.com/impress/impress.js/blob/cd499ed8cf1014d7151d21c94771a7495b379106/js/impress.js#L2323)

**Comment by najamelan** [comment]
Basically the bug is [here](https://github.com/impress/impress.js/blob/cd499ed8cf1014d7151d21c94771a7495b379106/js/impress.js#L2321). The onclick  property is being added inside the style element, so needless to say it doesn't do anything when you click the button.

**Comment by henrikingo** [comment]
Ah thanks! There are several bugs now surfacing with impressConsole.js getting more exposure. If nobody beats me to it, I'll work on them after we survive holiday season.

**Comment by henrikingo** [comment]
Required some additional work to actually make the button clickable. Thanks for filing this. It always bothered me why the button did nothing useful, then I forgot about the issue as I got used to it. But now it's finally fixed!

**Comment by najamelan** [comment]
Cool! I love how fluid it is to contribute to open source projects thanks to github.
