### ISSUE TITLE
Add Pointer support to impress.js presentations

### ISSUE THREAD

**Issue by fumblehool** [impress/impress.js#667]
Feature Request/Idea : A way to add pointer to an impress.js presentation.
Basically, the mouse pointer will convert to a pointer. 

The basic idea is : I want my mouse pointer to become a red dot (laser pointer) while presenting impress.js presentations. Some other options like thickness of pointer, color of pointer etc will be a big plus. I want to contribute to this feature, any ideas on how to go about achieving this. (maybe use some other tools to support etc)?

**Comment by henrikingo** [comment]
Hi @fumblehool 

Good news: This is already supported! You can define your mouse pointer in CSS, to make it look like anything you want.

In the demo presentations you find within impress.js, we use the `cursor:` CSS command to simply hide the mouse cursor during inactictivity: https://github.com/impress/impress.js/blob/master/css/impress-demo.css#L557

If you'd like an option where you'd turn this "laser pointer" on or off, or set its size, dynamically during the presentation, then you'll need some javascript. You could have a look at the `toolbar` plugin and some plugins using it (`autoplay`, `navigation`).

**Comment by henrikingo** [comment]
Closed with the assumption that using CSS is sufficient solution. If you have further questions or suggestions, feel free to reopen.
