### ISSUE TITLE
Feature request: Position steps relative to *any* previous step

### ISSUE THREAD

**Issue by complanar** [impress/impress.js#670]
Hovercraft has support for positioning relative to *any* previous step.
It would be great to get that, too as it makes positioning much easier, when creating presentations that have a complicated spatial structure.

There would be a need to introduce some kind of `data-rel-to` attribute.

**Comment by henrikingo** [comment]
This is a good and simple suggestion, and could easily be added to the `rel` plugin.

I can see the use case where slides are positioned relative to their previous title slide. Making each "section" of a presentation positioned together.

**Comment by henrikingo** [comment]
Implemented by  #686
