### ISSUE TITLE
Add version 1.0.0 to npm

### ISSUE THREAD

**Issue by stritti** [impress/impress.js#679]
Version 1.0.0 is missing on npm: https://www.npmjs.com/package/impress.js

**Comment by henrikingo** [comment]
Thanks for reminding. I had also forgotten to remove beta label from a few version strings in the repo itself, so did that now.

**Comment by henrikingo** [comment]
Ok, Google and StackOverflow are divided on this, so let's discuss here: Please let me know what you want in an npm package:

1) Just `js/impress.js`
2) also `src/` and `test/` (The argument for these is that someone might want to execute `npm test module`.)
3) Also the demo presentations. Arguably they are documentation. (Note that `extras/` **will** be empty, so in any case some slides under `examples/` will be broken if included.)

**Comment by stritti** [comment]
My 50 Cents:
I would prefer option 2, but would add an directory 'dist' (for distribution) containing the referable impress.js (and probably minified version impress.min.js).

Most libs I am using are following somehow this option.

**Comment by henrikingo** [comment]
For historical reasons, `js/impress.js` is the "dist". Currently it is not possible to create a minified version, as I've used EcmaScript 6 in some places and buildify didn't support that. (#663)

**Comment by henrikingo** [comment]
Ok. (2) is 4x as large as (1) and (3) was 1000 times! So I went with (2). It's now published!
