### ISSUE TITLE
splitting Presentation with a lot content

### ISSUE THREAD

**Issue by stritti** [impress/impress.js#688]
Is it possible to split a presentation with a lot content in several files and load them seamless on demand?

**Comment by henrikingo** [comment]
There's no specific functionality for it, but using regular HTML and JavaScript, sure. And, if you have a lot of content, loading it in parts is certainly a good idea!

The simple option is to just add a normal <a> hyperlink to the last slide, saying something like "next section" and pointing to your next html file.

On each slide transition, impress will emit an "impress:stepleave" event. You could add an event listener in JavaScript that detects when you're done with the last slide and loads the next html file automatically.

PS: The [mobile plugin](https://github.com/impress/impress.js/blob/master/src/plugins/mobile/README.md) actually offers related functionality. Not exactly what you asked, but worth mentioning.

**Comment by stritti** [comment]
Thanks @henrikingo. Currently I added a hyperlink to click as mentioned. But I will have a look in the events because I would prefer a "mousless" navigation :) Thanks for your hints

**Comment by stritti** [comment]
I've used following snipped (works for me):
```
/**
 * Module to load next impress file if attribute "data-next-impress" is defined.
* e.g.: <section id="Last" class="step"  data-next-impress="develop.html">...</section>
 */

/* global document, navigator */
(function (document) {
	"use strict";

	// Add prev and next classes to the siblings of the newly entered active step element
	// Remove prev and next classes from their current step elements
	document.addEventListener("impress:stepenter", function (event) {

		var nextImpress = event.srcElement.dataset.nextImpress;
		console.log(event);
		if ( nextImpress !== undefined ) {
			console.log("Load next impress file: " + nextImpress);
			document.addEventListener( "impress:stepleave", function() {
				window.location = nextImpress;
		  }, false );
		}



	});
})(document);
```
