### ISSUE TITLE
Impress.js odd touch/swipe in iOS Safari browser, fallback mode not initiating

### ISSUE THREAD

**Issue by ahainen** [impress/impress.js#690]
Ahoy - I'm trying this on an iPhone 6, iOS v11.2.6 15D100. I noticed as well that https://impress.js.org doesn't work in iOS Safari. i.e. It's not popping fallback mode and swiping makes the images scale/slide bizarrely. 

I'm fine getting impress.js to Fallback mode on mobile, but I can't seem to do that at all :/ https://ahainen.com/akroma/roadmap-2018-q2

Example: https://i.imgur.com/bMNcvvt.gifv

Let me know if I can provide more details

**Comment by henrikingo** [comment]
Also I have seen on some of my devices that the steps zoom to something really big during a swipe. Once the transition completes, the end result is correctly sized though. Is this the symptom you're reporting too?

Btw, to force the fallback mode, you can nowadays "unload" impress with such  a link:

    <a href="#" onclick="impress().tear();">Fallback mode / Disable 3D</a>

**Comment by tonystar** [comment]
> Also I have seen on some of my devices that the steps zoom to something really big during a swipe. Once the transition completes, the end result is correctly sized though. Is this the symptom you're reporting too?
Yes, I think this is what was meant by @ahainen. Same to me.
