### ISSUE TITLE
Add impress:substep:enter and impress:substep:leave events

### ISSUE THREAD

**Issue by henrikingo** [impress/impress.js#695]
to trigger an action (alert for instance), I simply add function like

    $("#foo").on('impress:stepenter',function(){
       alert("triggered");
    });

Is there a way to trigger an action on substep show? For example

    $("#fooSubstep").on('impress:substep:enter',function(){
       alert("triggered from substep #fooSubstep");
    });

(via email)

**Comment by henrikingo** [comment]
Yes. I'm open to a PR.

In general impress and its modules only trigger events that were needed by some other module, but we can add more as requested.

**Comment by willamesoares** [comment]
Hey @henrikingo, I saw that we have the `onSubstepShow` and `onSubstepHide` functions implemented. Are those the ones that needed to be implemented for this? Let me know.

**Comment by henrikingo** [comment]
No, those are used internally in impressConsole.js. This issue is still waiting for a PR.

**Comment by willamesoares** [comment]
Hey @henrikingo I've just opened #730 for adding the new events for the substep plugin.
Let me know what you think. Thanks

**Comment by henrikingo** [comment]
Thanks!
