### ISSUE TITLE
data-autoplay="7" just for one slide

### ISSUE THREAD

**Issue by srhuels** [impress/impress.js#701]
Hi Folks,

i try to use the step funktion with the autoplay attribute for just one (!!) slide

--> I want to stop autoplay at the last point of substeps.
The presentation should not switch to the next slide, until i pushed the spacebutton?

Tryd everything, don 't know how i should get it work.

Any Idea?

**Comment by henrikingo** [comment]
If you set `data-autoplay="0"` on a step, it should stop at that step. You can also just set `data-autoplay="10"` on a single step, but not the impress div, and then it should stop on all steps where autoplay is not set (or zero).

**Comment by srhuels** [comment]
Yes, that work fine. But i want to stop the autoplay bevore(!!!) the presentation goes to the next slide, where i can set autoplay=0!

**Comment by srhuels** [comment]
sorry henrikingo,

what should i explain additional?
I want to present f.e. 4 points in a slide, tell somthing about this point etc.
this means, i want to tell also something about the last "autoplayed" point(substep), before the presentation switches to the next slide.

But if i define autoplay=3 the slide with my substeps switches to the next slide after 3 seconds.
But it should not switch to the next slide, before i want!!

The autoplay - Parameter "0" in the nextc slide works, but just after the next slide ist aktive. The autoplay should stop at the end of the slide with the substeps!
You know what i mean?

**Comment by henrikingo** [comment]
Ah, sorry. I missed that your first question does indeed ask about substeps.

Right, this is not possible. You cannot set autoplay time for substeps, they get it from the step they are part of. Support for substeps could be added, but starts to feel convoluted, I don't know if I like it.

In your case a simple workaround would be to just add an invisible step right after the one you want to stop at. Same coordinates. Then add `data-autoplay="0"` to that.

Also, you can choose to not use autoplay at all, or set it to 0 for that slide, and just do it yourself in JavaScript:
    document.addEventListener( "impress:stepenter", function( event ) {
        if ( event.target.id == "your_special_step" ) {
            setTimeout( function() { impress().next(); }, 3000 );
            setTimeout( function() { impress().next(); }, 6000 );
            setTimeout( function() { impress().next(); }, 9000 );
            // Nothing for 4th substep
        }
    });

**Comment by srhuels** [comment]
Can you please links a webside with explanation for using such code for JS newbies?
I don't understand how to...

**Comment by srhuels** [comment]
OK, i got it work!
in the step ID with the substeps:
`style="opacity: 100"`
because it should be visible during the next step.

To stop the data-autopla i use an invisible empty step:
`<div class="step" style="opacity: 0" data-rel-x="0" data-rel-y="0" data-autoplay="0"></div>`
data-rel... is set to zero for staying the empty step at the same place as the step bevore with my substeps...
