### ISSUE TITLE
Application tries to trigger SetState on an unmounted component

### ISSUE THREAD

**Issue by kamilogram** [impress/impress.js#708]
There is a need to remove event listeners when Impress is unmounting. In my project, I use this library only on a desktop version of my project. When I'm resizing my site to mobile view, this Impress component is unmounting, but events still try to trigger a SetState, which throws an error.

**Comment by henrikingo** [comment]
You need to call impress().tear() to "uninitialize" impress. If some events trigger even after this, please file a more specific bug report.
