### ISSUE TITLE
Allow Maruku dialect for Markdown

### ISSUE THREAD

**Issue by ReDucTor** [impress/impress.js#724]
It would be nice to be able to use the Maruku dialect from the markdown-js library instead of Gruber this provides some extra functionality such as tables and even some meta handling that would potentially allow the power to have presenter notes within markdown

**Comment by henrikingo** [comment]
Good suggestion. (And one I've heard before, but couldn't find a duplicate issue, so maybe it was email or elsewhere.)

This could be supported by reading an attribute and passing it to the markdown library. Proposed syntax:

    <div class="step markdown" data-extras-markdown-dialect="Maruku">

This is the place to add it:
https://github.com/impress/impress.js/blob/97546a5536f762ff7948c771896723a48309c89b/src/plugins/extras/extras.js#L18-L52

**Comment by shakti97** [comment]
Would like to work on it

**Comment by govardhan27** [comment]
Hi is there anyone working on this?
If not I would like to take it up!

**Comment by henrikingo** [comment]
Please just send a PR when you have something to share.

**Comment by govardhan27** [comment]
ok thank you I will send a PR once done

**Comment by govardhan27** [comment]
@henrikingo Can you help me with how to work on this?
I am having a bit of trouble understanding.

**Comment by henrikingo** [comment]
I can help, but can you ask a specific question? My comment above should already help you get started in the right place.
