### ISSUE TITLE
impress.js no longer working?

### ISSUE THREAD

**Issue by PathosEthosLogos** [impress/impress.js#725]
It seems that the last update for impress.js is a year ago. Does it still work with the latest Firefox version?

https://www.youtube.com/watch?v=AZRtI8TOS7g

I followed the above video step by step, but it did not work for me.

**Comment by mohe2015** [comment]
@PathosEthosLogos  I didn't follow the tutorial but it seems that it should work. You should definitely check your browser console for errors. It may also be easier to use the https://github.com/impress/impress.js/blob/master/index.html example presentation and start from there

**Comment by henrikingo** [comment]
Hi @PathosEthosLogos 

The video is about [impressionist](https://github.com/henrikingo/impressionist), and as you note, haven't been updated in a while. impress.js itself (the core rendering engine) definitively works.

Although I've been more focused on impress.js for the past two years, I definitively still intend to work on impressionist too, sooner or later. It's still in development state and may or may not work. Recently [this Mac specific bug](https://github.com/henrikingo/impressionist/issues/19) was reported and isn't fixed yet.
