### ISSUE TITLE
presentations run from the filesystem in mac seem to have other size canvas

### ISSUE THREAD

**Issue by bryanrasmussen** [impress/impress.js#732]
I have had this experience with multiple presentations, including the official demo presentation:

I have viewed the presentation in either Chrome, Safari, and Firefox (developer, but I don't think it makes any difference) online, and everything works fine. I then save the presentation and open it in the same browser locally, and some are all of the slides won't work (meaning that you can navigate to slides but you will not see anything) in the case of the demo the first 3 slides do not show up, once I have navigated past step-3 to title I start seeing slides.

If I navigate through the whole presentation and get to overview and click the forward arrow going to bored all the slides move down out of the viewport and no slide is shown, navigating through the slides repeats the experience of before -  #bored, #step-2, and #step-3 do not show in the viewport.

OS Mac Mojave
Browsers Firefox Developer aurora update channel
Google Chrome 74.0.3729.108 (Official Build) (64-bit)
Safari version 12.1

**Comment by henrikingo** [comment]
I see the same (on a Linux laptop), or in any case don't see the correct slide show. In addition, I can see 2 toolbars when I open the saved presentation.

The explanation is that when you save a web page with the browser, the browser actually makes a lot of modifications to it. There's nothing we can do in impress.js to prevent this.

In practice, you have to copy the presentation (index.html + all other files / entire directory) in its raw form, without a browser. For the official demo, this means to check out the git repository, or to [download the release zip file](https://github.com/impress/impress.js/releases/tag/1.0.0).
