### ISSUE TITLE
Fallback message is shown even though impress is supported in the browser

### ISSUE THREAD

**Issue by PureTryOut** [impress/impress.js#737]
The class `impress-not-supported` in `body` is replaced with `impress-supported` correctly, but the `div` with the class `fallback-message` is shown nonetheless. This happens on Firefox 67.

**Comment by henrikingo** [comment]
I have Firefox 67 too and it's definitively working. Typically what you experience would be caused by some JavaScript error in your presentation. Have you looked at Web Developer > Web Console?

**Comment by henrikingo** [comment]
Closing old issue.
