### ISSUE TITLE
3d rotation problem?

### ISSUE THREAD

**Issue by sthielo** [impress/impress.js#740]
The attached files (html & css with latest version from master branch as of 2019-08-09) show some unexpected 3d behavior. order of translation and rotation transformations? not correct reset of origin for same rotation values? What would the correct values be for the expected behavior (see comments within the html file
[debug3d.zip](https://github.com/impress/impress.js/files/3487639/debug3d.zip)

tested with release tagged 1.0.0
tested with latest Chrome and Firefox

**Comment by sthielo** [comment]
I gt it. I wrongly assumed the order of translation and rotation! rotation happens BEFORE translation, which I found playing around with stacks off slides on all axis (see attachment)
[debug3d_stacks.zip](https://github.com/impress/impress.js/files/3488708/debug3d_stacks.zip)

Is there a way to define translation and rotation order? For my original intent I will just use another coordinate system and place the 'overview' (the perspective viewpoint) to fancy coords and angle, such that I can use simple ccords for the rest. This way I can ccircumvent most complex coord calculations. Is that how it is thought to be used?

**Comment by henrikingo** [comment]
Yes. See [this example](https://github.com/impress/impress.js/blob/master/examples/3D-rotations/index.html) for `data-rotate-order`.
