### ISSUE TITLE
Unable to get a useful navigation/toolbar/mobile experience

### ISSUE THREAD

**Issue by bizmate** [impress/impress.js#766]
Hi

My presentation looks great on desktop but on mobile I tried anything prebuilt i could find in the plugins but nothing works. Extract from my code

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=1024" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title>Portfolio</title>

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:regular,semibold,italic,italicsemibold|PT+Sans:400,700,400italic,700italic|PT+Serif:400,700,400italic,700italic" rel="stylesheet" />

    <link href="css/style.css" rel="stylesheet" />
</head>

<body class="impress-not-supported">
<div class="fallback-message">
    <p>Your browser <b>doesn't support the features required</b> by this presentation, so you are presented with a simplified version.</p>
    <p>For the best experience please use the latest <b>Chrome</b>, <b>Safari</b> or <b>Firefox</b> browser.</p>
</div>

<div id="impress">
     <div id="start" class="step" data-x="0" data-y="0" data-z="0" data-rotate-x="0" data-rotate-y="0" data-scale="1">.....
    </div>
    <div id="social" class="step slide" data-x="30000" data-y="0" style="">
    	......
    </div>
    <div id="thankyou" class="step " data-x="0" data-y="2000" data-z="7500" data-rotate-x="0" style="padding-top:200px">
    	<q>Thank you for your attention</q>
    </div>
</div>
<div class="hint" >
    <p style="width:75%;padding-left:15%"> Use a spacebar or arrow keys to navigate </p>
</div>
<div id="impress-toolbar"></div>
<div id="impress-navigation-ui"></div>
<div id="impress-navigation"></div>
<script src="js/impress.js"></script>
<script>
	impress().init();
</script>
<script src="plugins/toolbar.js"></script>
<script src="plugins/navigation.js"></script>
<script src="plugins/navigation-ui.js"></script>
</body>
</html>
```
If I understand well all it will do here is that the #impress-toolbar element is used and then the navigation and navigation-ui should do something on top of it but the only thing I can see is that when i switch slide with the usual controls the slide id is shown. The controls and autoplay are not working and no errors in console.log .

The problem is crucial on mobile where sliding is really a bad experience. Ideally what i was looking for:
- be able to press either a bottom next or previous slide button like prezi has
- alternative a vertically aligned in the middle left and right buttons/arrows like a carousel
- on another note, i tried to integrate a script to render it full screen on mobile (ideally no address bar should be shown) -> https://sindresorhus.com/screenfull.js/ as found at https://developers.google.com/web/fundamentals/native-hardware/fullscreen but once added a button to do the full screen it was not working, again no console.log and my JS is not advanced.

Any suggestions?

**Comment by henrikingo** [comment]
If I understood you correctly, swiping works but you don't like it?

Maybe the easiest is to modify the CSS for the toolbar so that it always shows (remote the hiding on mousetimeout) and then of course you can make the buttons larger, transparent, etc.

**Comment by bizmate** [comment]
swiping is too clunky/difficult to control but the main problem is that the toolbar is not working for me else I would have tried to customise it with CSS. As I wrote in the previous body about toolbar/navigation/navigation ui ....

```
The controls and autoplay are not working and no errors in console.log .
```

Pressing the toolbar buttons does not work, but also i see no difference in adding the navigation and navigation-ui scripts/JS in the page.

**Comment by henrikingo** [comment]
You should only add js/impress.js. The files under src/ are copied into js/impress.js. More specifically, you shouldn't have these lines in your HTML:

    <div id="impress-navigation-ui"></div>
    <div id="impress-navigation"></div>
    <script src="plugins/toolbar.js"></script>
    <script src="plugins/navigation.js"></script>
    <script src="plugins/navigation-ui.js"></script>

Does the toolbar work on a laptop/PC with the mouse? It sounds like you may be missing this from your CSS: https://github.com/impress/impress.js/blob/ddfb5eb78cbee4b0aeb550c8df4f7764fa9ec9d6/css/impress-common.css#L140

**Comment by bizmate** [comment]
Thank you for the last message. I knew i didnt need those lines. The problem might have been caused by outdated src folder and also I did not have impress-common.css 

I have now added them but, compared to the impress.js.org, i had to explicitly include the css in the html such as `	<link href="css/impress-common.css" rel="stylesheet" />`

Apart from the above I really think the toolbar experience is not up to scratch for mobile. After getting the toolbar working I managed to customise it to make the arrows a bit more mobile friendly.

http://presents.bizmate.biz/ 

On mobile the difference in experience is massive, swiping is very bad in impress.js.org if you have quite a lot of 3d animations. It is probably ok on a standard presentation like layout, but on more advanced 3d animations it looks like you loose control of the app. The arrows styled in the middle are simple because they can be clicked easily. Maybe compare with impress.js.org

About the fullscreen plugin included in the project it looks like from the source code it is built with desktop in mind only so i will try again the script from the Google page.

I will let you close the ticket if you want but I really think a mobile-scroller (as opposed to toolbar) plugin would be great to make the project work on mobiles straight away and much better.
My js is not great but if I have time and can work out something i might do a PR

**Comment by bizmate** [comment]
BTW I have spotted some problems with my implementation on mobile. I will try to see what it is as it renders fine for some mobiles but in some cases i noticed the style is not applied on mobile

**Comment by henrikingo** [comment]
Hi. I'm glad to see you got it working.

The impress-common.css is really just suggested CSS. So it is quite intended that you can style the buttons differently. I like what you managed to do with them. You are right that when I have designed the toolbar the way it is in impress.js.org, I have not at all targeted mobile devices. Also back then impress.js didn't target mobile devices due to amount of memory required.

impress-common.css was just added, and impress.js.org often lags behind what you see in the master git repository, so this explains why you didn't see it.

And I also agree that swiping is counter intuitive if the presentation layout doesn't follow the left-right directions of the swipes. (e.g. for https://impress.js.org/examples/classic-slides/ it works nicely.) Otoh it seems swiping is preferred over buttons by many users on touch devices. So all I can do is offer both and let you choose. If there would evolve some consensus on this topic, we can of course make changes in the future.
