### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [impress/impress.js#770]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by henrikingo** [comment]
Hi

I don't know why I have missed this. This is actually a good suggestion. I don't even have access to the analytics account I think, it's been added before I was maintainer. I will reopen and do this at some point.

**Comment by henrikingo** [comment]
(Or, PRs welcome too, of course.)
