### ISSUE TITLE
FR: Remove F5 as keyboard shortcut

### ISSUE THREAD

**Issue by DarkTrick** [impress/impress.js#786]
Problem:
- `F5` is the global standard shortcut for reloading a website. 
- Using impress.js requires a lot of trial-and-error (because text-based); I.e. reloading is necessary frequently

Suggestion:
- Use `Ctrl` + `F5` instead (didn't check for compatibility problems outside of firefox)

**Comment by henrikingo** [comment]
Hi. F5 is used for "PowerPoint compatibility". In practice this means compatibility with remote controllers.

This binding comes from the https://github.com/impress/impress.js/blob/master/src/plugins/fullscreen/fullscreen.js plugin. Just [disable this plugin](https://github.com/impress/impress.js/blob/f68e5fff298469cf9836fa6121f665d8ab323e2a/build.js#L14) if you don't want it.

Note that browsers will also reload the page if you press Ctrl+R. This works with impress.js.
