### ISSUE TITLE
How do I launch the program

### ISSUE THREAD

**Issue by Animyos** [impress/impress.js#787]
Hello!
I've downloaded the files of version 1.1.0 from SourceForge, and the demo file looks amazing. But how do I install / launch the program to design presentations myself? There is no .exe file or something familiar.

Screenshot in the attachment.

Kind regards
Linus Sturm aka AnimyosFox
![Anmerkung 2021-05-26 152351](https://user-images.githubusercontent.com/82672160/119667262-69f35c00-be36-11eb-887c-6deb03e43bc5.png)

**Comment by henrikingo** [comment]
Hi Animyos

Indeed there is no exe file. Most commonly people create the HTML code themselves. If you open the demo again and select "View source" or press "Ctrl+U" you will see that the demo on the inside is actually a written tutorial for how to create presentations. Also the other demos have the same: https://impress.js.org/examples/

More, maybe easier tutorials are available at https://github.com/impress/impress.js/wiki/impress.js-tutorials-and-other-learning-resources

If you've never created HTML pages before, this might be difficult for you. There are a number of visual editor tools created, but all (including mine) are kind of unfinished and I can't recommend any of them unfortunately.

henrik

**Comment by Animyos** [comment]
Ok, thanks. I know how to edit HTML and can recommend Visual studio code or Notepad ++.

Kind regards
Linus Sturm aka AnimyosFox

**Comment by henrikingo** [comment]
Excellent! You will do well then. Enjoy!
