### ISSUE TITLE
Exclude Visual Element From Direct Access

### ISSUE THREAD

**Issue by danny** [impress/impress.js#8]
So I really like this tool, but I thought it'd be cool to be able to position elements on the canvas but not have them as slides - i.e. you only view them when zooming/moving etc.  I implemented this functionality by including  a new attribute: data-exclude="true" (defaults to false if not present so it doesn't break existing code).

`<div id="its" class="step" **data-exclude="true"** data-x="850" data-y="0" data-rotate="90" data-scale="5">`

And I filter the steps right before the select method is set, insert @ line 180:

```
var tempSteps = [];
for (var i = 0; i < steps.length; i++)
{
  if(!steps[i].dataset['exclude'] && true)
    tempSteps.push(steps[i]);
}    
steps = tempSteps; 

//make given step active
```

I didn't want to issue a pull request since this is a new feature, and I'm not sure what the design/style of this js file will be, I can issue one if you'd like.

**Comment by henrikingo** [comment]
Hi @danny 

As you may have noticed, I've been working on adding a new plugin api to impress.js, and then on adding new features as plugins. It now has a [skip plugin](https://github.com/henrikingo/impress.js/blob/myfork/src/plugins/skip/README.md) which can be used to add steps to a presentation, which will nevertheless be skipped when navigating through the presentation.

**Comment by henrikingo** [comment]
skip plugin is now merged to impress.js master
