### ISSUE TITLE
Upgrade Markdown parser 

### ISSUE THREAD

**Issue by thawk** [impress/impress.js#811]
It seems that `extras/markdown/markdown.js` is a quite old version.  In that file, the last updated date is marked as `2013-09-15T16:12Z`.
Suggest to upgrade it to a more modern version, or replace by another parser.
I've tried using [marked](https://github.com/markedjs/marked), it's as easy as replacing one line in `plugins/extras/extras.js`.

**Comment by henrikingo** [comment]
+1
I'd welcome a PR for sure.

**Comment by thawk** [comment]
Closed by #817
