### ISSUE TITLE
Trim common leading indention for Markdown

### ISSUE THREAD

**Issue by thawk** [impress/impress.js#812]
Currently, additional indentions is not allowed for Markdown, it will be recognized as [indented code block](https://spec.commonmark.org/0.30/#indented-code-block).  This makes it hard to using HTML formatter to format the code.

Suggest to remove the common leading indention for a Markdown code block.  We can use the first non-blank line to detect the amount of leading spaces, than remove them before feeding to Markdown parser.

**Comment by henrikingo** [comment]
Makes sense. I always write the Markdown left aligned, but a html editor may disagree with that, sure.

Oh, that reminds me... Filed #813 to capture an idea I had some years ago but apparently never created an issue.

**Comment by thawk** [comment]
Closed by #817
