### ISSUE TITLE
Set `data-transition-duration` for each step separately

### ISSUE THREAD

**Issue by SMSadegh19** [impress/impress.js#819]
Hi!
I want to set `data-transition-duration` for each step separately, but it seems there is no feature to do this.
As I think `data-transition-duration` is just for the `impress` class.

**Comment by henrikingo** [comment]
It should also be possible to set individually for each step: https://github.com/impress/impress.js/blob/629f7686f3b95900fc97bcd901cb4d564769c2ee/examples/classic-slides/index.html#L429

Is this not working for you?

**Comment by SMSadegh19** [comment]
Thanks a lot.
