### ISSUE TITLE
the release notes state the default resolution is 1920 x 1800 full HD ??

### ISSUE THREAD

**Issue by pmario** [impress/impress.js#820]
the release notes state the default resolution is 1920 x 1800 ... full HD is 1920 x 1080

The second sentence in the rel-notes also states. 

>In addition the max scale factor by default is now 3 x the default,

which doesn't make too much sense for me. Please check that.

**Comment by henrikingo** [comment]
Thanks for this. 

> the release notes state the default resolution is 1920 x 1800 ... full HD is 1920 x 1080

To be pedantic:
* Default width in code is correct, 1080: https://github.com/impress/impress.js/blob/dc3cf69747e0b1b0d1fe534509d09c3c48030e68/src/impress.js#L171
* DOCUMENTATION.md is also correct. https://github.com/impress/impress.js/blob/master/DOCUMENTATION.md#root-element

**Comment by pmario** [comment]
Thanks for the detailed info and it's nice to see, that there are still improvements implemented, for an already great software.
