### ISSUE TITLE
New Website - Suggestions

### ISSUE THREAD

**Issue by simplePCBuilding** [impress/impress.js#837]
I am currently working on a new website. I am currently elaborating my font choices, but I can't seem to come to a conclusion. Any suggestions? You can find the current state of development [here](https://github.com/simplePCBuilding/impress.js/tree/new-impress-website)

**Comment by simplePCBuilding** [comment]
I have some suggestions for fonts (just head to fonts.google.com and search for the font):

- Imprima
- Ubuntu
- Quicksand
- Josefin Sans
- Exo 2

Some random suggestions I liked, but may not be the best...
- Lobster
- Cairo
- Dancing Script
- Pacifico

**Comment by simplePCBuilding** [comment]
I have now started thinking about how to implement docs. I was thinking about using readthedocs first, but then I wanted to do it on my own using mdToHtml, as I feel like that'd be the easiest.

**Comment by simplePCBuilding** [comment]
I was thinking about just loading and unloading the selected pages, so we technically just have one wiki page with impress-like urls

**Comment by henrikingo** [comment]
This is hard to comment on without seeing some concrete demo/example.

But thank you for doing this, I really appreciate it.

**Comment by simplePCBuilding** [comment]
I can upload a demo to https://impress-testing.janishutz.com this evening, maybe this afternoon, if I don't get IP blocked by DirectAdmin.

**Comment by simplePCBuilding** [comment]
okay I am kinda forgetful, so I forgot, but added a reminder and will add it in about 2-3 hours

**Comment by simplePCBuilding** [comment]
I have spend some more time thinking about how the documentation should be assembled. I feel like I should create a script that automatically takes all the README.md files of the plugins, the Getting Started Guide and some custom pages. I will use the DOCUMENTATION.md and README.md files of impress itself to create a more user friendly experience that is just on the website with simple navigation. This should allow new users to have a more curated experience whilst obviously still having the repo for more advanced users.

**Comment by henrikingo** [comment]
Okay that sounds like a good start!

**Comment by simplePCBuilding** [comment]
Didn't think about that, great suggestion. I just noticed it is sorta confusing on mobile sometimes.

And about different repository... I think that would be the best idea

**Comment by simplePCBuilding** [comment]
I have also noticed another problem. The links in the MD are relative ones. I would need to build a full source map to correctly link between the files. I have an idea on how to do it, which would require that a change to the repo structure will also be made to the link replacing unit.

**Comment by simplePCBuilding** [comment]
I have mostly figured out the link parsing. I will finish it probably either this afternoon or this evening (it is currently 10:30AM for me)

**Comment by simplePCBuilding** [comment]
I have also run into a problem with syncing my fork. There are merge conflicts. How do I update my fork from the command line?

**Comment by simplePCBuilding** [comment]
I will today also update the demo website (https://impress-testing.janishutz.com/) with the newest changes from my fork

**Comment by simplePCBuilding** [comment]
https://github.com/impress/impress.js/pull/847 continuing there
