### ISSUE TITLE
Should the goto plugin support non-navigation input keys?

### ISSUE THREAD

**Issue by mengwong** [impress/impress.js#850]
Currently, the goto plugin recognizes keys like `ArrowUp`, `ArrowDown` in `data-goto-key-list`.

Wouldn't it be nice if the goto plugin could recognize keys like `KeyA`, `KeyB`, `Digit1`, `Digit2` as well?

Unless there is a good reason not to do this, I will fork and work toward submitting a PR to support this feature.

**Comment by simplePCBuilding** [comment]
Hhm. What would be the reason for it? I am pretty sure space bar is already in the list. Would you then in that case map the keystroke to a specific step with something like  
```
data-goto-step-key="A"
```
?

**Comment by mengwong** [comment]
yes, I will PR a working demo. I thought about it a bit more and realized I was implementing bookmark hotkeys, so I have done it as a `bookmark` plugin, extending the existing 2d navigation.

**Comment by simplePCBuilding** [comment]
I think you can close this issue now, as you have opened the PR, same with the other one
