### ISSUE TITLE
Different movement profiles in CORE

### ISSUE THREAD

**Issue by simplePCBuilding** [impress/impress.js#854]
I was thinking about transitioning between steps a lot lately and I think, it'd be cool if we could choose between multiple different transition profiles with an optional `data-transition-mode=""` attribute, where you could choose between default (active if no `data-transition-mode` specified or it is "default"), zoom-out-zoom-in (zooms out slightly and then back in whilst moving), the opposite (zoom-in-zoom-out) and flat (does not accelerate or decelerate, just starts end stops immediately). 

Any ideas on what to add or what not to implement or any other thoughts on this idea?

**Comment by simplePCBuilding** [comment]
I am pretty sure this is not possible to implement as a plugin currently, right? I could also try and implement plugin support for this

**Comment by simplePCBuilding** [comment]
I will open a new Issue explaining this in a completely different way with an entirely different approach

**Comment by henrikingo** [comment]
Yes, but same comment here as I did a few minutes ago in a different issue: You should always first exhaust what can already be done with regular CSS and zero lines of JavaScript. It will take you surprisingly far, which is the point of Slide 7 here: https://impress.js.org/examples/classic-slides/#/step-7

Once you've reached the limit, then adding plugins and data-attributes="..." is the right way.

**Comment by simplePCBuilding** [comment]
Yeah I know, what this is about is that it's about the slides, so transition between the slides. I don't think that that's possible with CSS only
