### ISSUE TITLE
Disable autoplay?

### ISSUE THREAD

**Issue by b1ek** [impress/impress.js#862]
Hey y'all, I am building a presentation with this framework, and I find that feature annoying. Is there an option to disable it for the presentation?

**Comment by simplePCBuilding** [comment]
Yes, you can do this by omitting the data-autoplay argument in the `<div id="impress" data-autoplay="0"></div>` or by setting it to 0. See the docs [here](https://impress-testing.janishutz.com/docs/plugins/autoplay.html) (that's from the upcoming impress.js website). @b1ek

**Comment by b1ek** [comment]
> Yes, you can do this by omitting the data-autoplay argument in the `<div id="impress" data-autoplay="0"></div>` or by setting it to 0. See the docs [here](https://impress-testing.janishutz.com/docs/plugins/autoplay.html) (that's from the upcoming impress.js website). @b1ek

I see. Thank you!
