### ISSUE TITLE
Disable mouse navigation?

### ISSUE THREAD

**Issue by b1ek** [impress/impress.js#865]
I noticed that when I click on a `.step` element, the presentation jumps right to it. Is there any way to disable this?

I dont want to do `.step { pointer-events: none }` since my steps contain clickable elements

**Comment by simplePCBuilding** [comment]
I will have to look into this in more details, as I don't remember. If this isn't a thing yet, I will be adding this in the refactor for V3 I am currently planning. Couldn't you just do a 

`.whateversubclass { pointer-events: auto }`

on all the ones where you actually need the events and do

`.step { pointer-events: none }`?

I hope this helps for now, I will have a look at the impress.js code base on this matter as I don't remember how exactly those events are handled.

**Comment by b1ek** [comment]
> I will have to look into this in more details, as I don't remember. If this isn't a thing yet, I will be adding this in the refactor for V3 I am currently planning. Couldn't you just do a
> 
> `.whateversubclass { pointer-events: auto }`
> 
> on all the ones where you actually need the events and do
> 
> `.step { pointer-events: none }`?
> 
> I hope this helps for now, I will have a look at the impress.js code base on this matter as I don't remember how exactly those events are handled.

I have figured out a little workaround:  
```css
.step { pointer-events: none }
.step.active { pointer-events: all }
```

But that is just that, a workaround. Im pretty sure that it would make sense to be able to click on another step (which is not the active one)

**Comment by simplePCBuilding** [comment]
I have added this to the todo list for V3.

**Comment by henrikingo** [comment]
> But that is just that, a workaround.

This is not a workaround, this is how impress is designed to work. You use CSS to make it behave how you want.

**Comment by henrikingo** [comment]
I will close this to keep the issues list tidy, but feel free to continue commenting or asking questions.
